/*
 * This file is generated by jOOQ.
 */
package vn.mcare.system.repository.model.tables.records;


import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;

import vn.mcare.system.repository.model.tables.Admin;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AdminRecord extends UpdatableRecordImpl<AdminRecord> implements Record9<String, String, String, String, String, String, LocalDateTime, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 613612905;

    /**
     * Setter for <code>thangvtm_mcare.admin.cif</code>.
     */
    public AdminRecord setCif(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.admin.cif</code>.
     */
    public String getCif() {
        return (String) get(0);
    }

    /**
     * Setter for <code>thangvtm_mcare.admin.email</code>.
     */
    public AdminRecord setEmail(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.admin.email</code>.
     */
    public String getEmail() {
        return (String) get(1);
    }

    /**
     * Setter for <code>thangvtm_mcare.admin.password</code>.
     */
    public AdminRecord setPassword(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.admin.password</code>.
     */
    public String getPassword() {
        return (String) get(2);
    }

    /**
     * Setter for <code>thangvtm_mcare.admin.salt</code>.
     */
    public AdminRecord setSalt(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.admin.salt</code>.
     */
    public String getSalt() {
        return (String) get(3);
    }

    /**
     * Setter for <code>thangvtm_mcare.admin.full_name</code>.
     */
    public AdminRecord setFullName(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.admin.full_name</code>.
     */
    public String getFullName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>thangvtm_mcare.admin.description</code>.
     */
    public AdminRecord setDescription(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.admin.description</code>.
     */
    public String getDescription() {
        return (String) get(5);
    }

    /**
     * Setter for <code>thangvtm_mcare.admin.last_login</code>.
     */
    public AdminRecord setLastLogin(LocalDateTime value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.admin.last_login</code>.
     */
    public LocalDateTime getLastLogin() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>thangvtm_mcare.admin.created_at</code>.
     */
    public AdminRecord setCreatedAt(LocalDateTime value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.admin.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>thangvtm_mcare.admin.modified_at</code>.
     */
    public AdminRecord setModifiedAt(LocalDateTime value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.admin.modified_at</code>.
     */
    public LocalDateTime getModifiedAt() {
        return (LocalDateTime) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<String, String, String, String, String, String, LocalDateTime, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<String, String, String, String, String, String, LocalDateTime, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Admin.ADMIN.CIF;
    }

    @Override
    public Field<String> field2() {
        return Admin.ADMIN.EMAIL;
    }

    @Override
    public Field<String> field3() {
        return Admin.ADMIN.PASSWORD;
    }

    @Override
    public Field<String> field4() {
        return Admin.ADMIN.SALT;
    }

    @Override
    public Field<String> field5() {
        return Admin.ADMIN.FULL_NAME;
    }

    @Override
    public Field<String> field6() {
        return Admin.ADMIN.DESCRIPTION;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return Admin.ADMIN.LAST_LOGIN;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return Admin.ADMIN.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field9() {
        return Admin.ADMIN.MODIFIED_AT;
    }

    @Override
    public String component1() {
        return getCif();
    }

    @Override
    public String component2() {
        return getEmail();
    }

    @Override
    public String component3() {
        return getPassword();
    }

    @Override
    public String component4() {
        return getSalt();
    }

    @Override
    public String component5() {
        return getFullName();
    }

    @Override
    public String component6() {
        return getDescription();
    }

    @Override
    public LocalDateTime component7() {
        return getLastLogin();
    }

    @Override
    public LocalDateTime component8() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component9() {
        return getModifiedAt();
    }

    @Override
    public String value1() {
        return getCif();
    }

    @Override
    public String value2() {
        return getEmail();
    }

    @Override
    public String value3() {
        return getPassword();
    }

    @Override
    public String value4() {
        return getSalt();
    }

    @Override
    public String value5() {
        return getFullName();
    }

    @Override
    public String value6() {
        return getDescription();
    }

    @Override
    public LocalDateTime value7() {
        return getLastLogin();
    }

    @Override
    public LocalDateTime value8() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value9() {
        return getModifiedAt();
    }

    @Override
    public AdminRecord value1(String value) {
        setCif(value);
        return this;
    }

    @Override
    public AdminRecord value2(String value) {
        setEmail(value);
        return this;
    }

    @Override
    public AdminRecord value3(String value) {
        setPassword(value);
        return this;
    }

    @Override
    public AdminRecord value4(String value) {
        setSalt(value);
        return this;
    }

    @Override
    public AdminRecord value5(String value) {
        setFullName(value);
        return this;
    }

    @Override
    public AdminRecord value6(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public AdminRecord value7(LocalDateTime value) {
        setLastLogin(value);
        return this;
    }

    @Override
    public AdminRecord value8(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public AdminRecord value9(LocalDateTime value) {
        setModifiedAt(value);
        return this;
    }

    @Override
    public AdminRecord values(String value1, String value2, String value3, String value4, String value5, String value6, LocalDateTime value7, LocalDateTime value8, LocalDateTime value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AdminRecord
     */
    public AdminRecord() {
        super(Admin.ADMIN);
    }

    /**
     * Create a detached, initialised AdminRecord
     */
    public AdminRecord(String cif, String email, String password, String salt, String fullName, String description, LocalDateTime lastLogin, LocalDateTime createdAt, LocalDateTime modifiedAt) {
        super(Admin.ADMIN);

        set(0, cif);
        set(1, email);
        set(2, password);
        set(3, salt);
        set(4, fullName);
        set(5, description);
        set(6, lastLogin);
        set(7, createdAt);
        set(8, modifiedAt);
    }
}
