/*
 * This file is generated by jOOQ.
 */
package vn.mcare.system.repository.model.tables.records;


import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;

import vn.mcare.system.repository.model.tables.Bill;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BillRecord extends UpdatableRecordImpl<BillRecord> implements Record13<String, Integer, LocalDateTime, Double, Boolean, Integer, Double, Double, String, String, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1256445550;

    /**
     * Setter for <code>thangvtm_mcare.bill.bill_id</code>.
     */
    public BillRecord setBillId(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.bill.bill_id</code>.
     */
    public String getBillId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>thangvtm_mcare.bill.bill_type</code>.
     */
    public BillRecord setBillType(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.bill.bill_type</code>.
     */
    public Integer getBillType() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>thangvtm_mcare.bill.bill_date</code>.
     */
    public BillRecord setBillDate(LocalDateTime value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.bill.bill_date</code>.
     */
    public LocalDateTime getBillDate() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>thangvtm_mcare.bill.sub_price</code>.
     */
    public BillRecord setSubPrice(Double value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.bill.sub_price</code>.
     */
    public Double getSubPrice() {
        return (Double) get(3);
    }

    /**
     * Setter for <code>thangvtm_mcare.bill.is_vat</code>.
     */
    public BillRecord setIsVat(Boolean value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.bill.is_vat</code>.
     */
    public Boolean getIsVat() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>thangvtm_mcare.bill.vat_rate</code>.
     */
    public BillRecord setVatRate(Integer value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.bill.vat_rate</code>.
     */
    public Integer getVatRate() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>thangvtm_mcare.bill.vat_price</code>.
     */
    public BillRecord setVatPrice(Double value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.bill.vat_price</code>.
     */
    public Double getVatPrice() {
        return (Double) get(6);
    }

    /**
     * Setter for <code>thangvtm_mcare.bill.total_price</code>.
     */
    public BillRecord setTotalPrice(Double value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.bill.total_price</code>.
     */
    public Double getTotalPrice() {
        return (Double) get(7);
    }

    /**
     * Setter for <code>thangvtm_mcare.bill.customer_id</code>.
     */
    public BillRecord setCustomerId(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.bill.customer_id</code>.
     */
    public String getCustomerId() {
        return (String) get(8);
    }

    /**
     * Setter for <code>thangvtm_mcare.bill.create_by</code>.
     */
    public BillRecord setCreateBy(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.bill.create_by</code>.
     */
    public String getCreateBy() {
        return (String) get(9);
    }

    /**
     * Setter for <code>thangvtm_mcare.bill.description</code>.
     */
    public BillRecord setDescription(String value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.bill.description</code>.
     */
    public String getDescription() {
        return (String) get(10);
    }

    /**
     * Setter for <code>thangvtm_mcare.bill.created_at</code>.
     */
    public BillRecord setCreatedAt(LocalDateTime value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.bill.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(11);
    }

    /**
     * Setter for <code>thangvtm_mcare.bill.modified_at</code>.
     */
    public BillRecord setModifiedAt(LocalDateTime value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.bill.modified_at</code>.
     */
    public LocalDateTime getModifiedAt() {
        return (LocalDateTime) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row13<String, Integer, LocalDateTime, Double, Boolean, Integer, Double, Double, String, String, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    @Override
    public Row13<String, Integer, LocalDateTime, Double, Boolean, Integer, Double, Double, String, String, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row13) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Bill.BILL.BILL_ID;
    }

    @Override
    public Field<Integer> field2() {
        return Bill.BILL.BILL_TYPE;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return Bill.BILL.BILL_DATE;
    }

    @Override
    public Field<Double> field4() {
        return Bill.BILL.SUB_PRICE;
    }

    @Override
    public Field<Boolean> field5() {
        return Bill.BILL.IS_VAT;
    }

    @Override
    public Field<Integer> field6() {
        return Bill.BILL.VAT_RATE;
    }

    @Override
    public Field<Double> field7() {
        return Bill.BILL.VAT_PRICE;
    }

    @Override
    public Field<Double> field8() {
        return Bill.BILL.TOTAL_PRICE;
    }

    @Override
    public Field<String> field9() {
        return Bill.BILL.CUSTOMER_ID;
    }

    @Override
    public Field<String> field10() {
        return Bill.BILL.CREATE_BY;
    }

    @Override
    public Field<String> field11() {
        return Bill.BILL.DESCRIPTION;
    }

    @Override
    public Field<LocalDateTime> field12() {
        return Bill.BILL.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field13() {
        return Bill.BILL.MODIFIED_AT;
    }

    @Override
    public String component1() {
        return getBillId();
    }

    @Override
    public Integer component2() {
        return getBillType();
    }

    @Override
    public LocalDateTime component3() {
        return getBillDate();
    }

    @Override
    public Double component4() {
        return getSubPrice();
    }

    @Override
    public Boolean component5() {
        return getIsVat();
    }

    @Override
    public Integer component6() {
        return getVatRate();
    }

    @Override
    public Double component7() {
        return getVatPrice();
    }

    @Override
    public Double component8() {
        return getTotalPrice();
    }

    @Override
    public String component9() {
        return getCustomerId();
    }

    @Override
    public String component10() {
        return getCreateBy();
    }

    @Override
    public String component11() {
        return getDescription();
    }

    @Override
    public LocalDateTime component12() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component13() {
        return getModifiedAt();
    }

    @Override
    public String value1() {
        return getBillId();
    }

    @Override
    public Integer value2() {
        return getBillType();
    }

    @Override
    public LocalDateTime value3() {
        return getBillDate();
    }

    @Override
    public Double value4() {
        return getSubPrice();
    }

    @Override
    public Boolean value5() {
        return getIsVat();
    }

    @Override
    public Integer value6() {
        return getVatRate();
    }

    @Override
    public Double value7() {
        return getVatPrice();
    }

    @Override
    public Double value8() {
        return getTotalPrice();
    }

    @Override
    public String value9() {
        return getCustomerId();
    }

    @Override
    public String value10() {
        return getCreateBy();
    }

    @Override
    public String value11() {
        return getDescription();
    }

    @Override
    public LocalDateTime value12() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value13() {
        return getModifiedAt();
    }

    @Override
    public BillRecord value1(String value) {
        setBillId(value);
        return this;
    }

    @Override
    public BillRecord value2(Integer value) {
        setBillType(value);
        return this;
    }

    @Override
    public BillRecord value3(LocalDateTime value) {
        setBillDate(value);
        return this;
    }

    @Override
    public BillRecord value4(Double value) {
        setSubPrice(value);
        return this;
    }

    @Override
    public BillRecord value5(Boolean value) {
        setIsVat(value);
        return this;
    }

    @Override
    public BillRecord value6(Integer value) {
        setVatRate(value);
        return this;
    }

    @Override
    public BillRecord value7(Double value) {
        setVatPrice(value);
        return this;
    }

    @Override
    public BillRecord value8(Double value) {
        setTotalPrice(value);
        return this;
    }

    @Override
    public BillRecord value9(String value) {
        setCustomerId(value);
        return this;
    }

    @Override
    public BillRecord value10(String value) {
        setCreateBy(value);
        return this;
    }

    @Override
    public BillRecord value11(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public BillRecord value12(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public BillRecord value13(LocalDateTime value) {
        setModifiedAt(value);
        return this;
    }

    @Override
    public BillRecord values(String value1, Integer value2, LocalDateTime value3, Double value4, Boolean value5, Integer value6, Double value7, Double value8, String value9, String value10, String value11, LocalDateTime value12, LocalDateTime value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BillRecord
     */
    public BillRecord() {
        super(Bill.BILL);
    }

    /**
     * Create a detached, initialised BillRecord
     */
    public BillRecord(String billId, Integer billType, LocalDateTime billDate, Double subPrice, Boolean isVat, Integer vatRate, Double vatPrice, Double totalPrice, String customerId, String createBy, String description, LocalDateTime createdAt, LocalDateTime modifiedAt) {
        super(Bill.BILL);

        set(0, billId);
        set(1, billType);
        set(2, billDate);
        set(3, subPrice);
        set(4, isVat);
        set(5, vatRate);
        set(6, vatPrice);
        set(7, totalPrice);
        set(8, customerId);
        set(9, createBy);
        set(10, description);
        set(11, createdAt);
        set(12, modifiedAt);
    }
}
