/*
 * This file is generated by jOOQ.
 */
package vn.mcare.system.repository.model.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;

import vn.mcare.system.repository.model.tables.ContentLayout;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContentLayoutRecord extends UpdatableRecordImpl<ContentLayoutRecord> implements Record4<String, String, String, String> {

    private static final long serialVersionUID = 85740620;

    /**
     * Setter for <code>thangvtm_mcare.content_layout.content_key</code>.
     */
    public ContentLayoutRecord setContentKey(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.content_layout.content_key</code>.
     */
    public String getContentKey() {
        return (String) get(0);
    }

    /**
     * Setter for <code>thangvtm_mcare.content_layout.title</code>.
     */
    public ContentLayoutRecord setTitle(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.content_layout.title</code>.
     */
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>thangvtm_mcare.content_layout.content</code>.
     */
    public ContentLayoutRecord setContent(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.content_layout.content</code>.
     */
    public String getContent() {
        return (String) get(2);
    }

    /**
     * Setter for <code>thangvtm_mcare.content_layout.description</code>.
     */
    public ContentLayoutRecord setDescription(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.content_layout.description</code>.
     */
    public String getDescription() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<String, String, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<String, String, String, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return ContentLayout.CONTENT_LAYOUT.CONTENT_KEY;
    }

    @Override
    public Field<String> field2() {
        return ContentLayout.CONTENT_LAYOUT.TITLE;
    }

    @Override
    public Field<String> field3() {
        return ContentLayout.CONTENT_LAYOUT.CONTENT;
    }

    @Override
    public Field<String> field4() {
        return ContentLayout.CONTENT_LAYOUT.DESCRIPTION;
    }

    @Override
    public String component1() {
        return getContentKey();
    }

    @Override
    public String component2() {
        return getTitle();
    }

    @Override
    public String component3() {
        return getContent();
    }

    @Override
    public String component4() {
        return getDescription();
    }

    @Override
    public String value1() {
        return getContentKey();
    }

    @Override
    public String value2() {
        return getTitle();
    }

    @Override
    public String value3() {
        return getContent();
    }

    @Override
    public String value4() {
        return getDescription();
    }

    @Override
    public ContentLayoutRecord value1(String value) {
        setContentKey(value);
        return this;
    }

    @Override
    public ContentLayoutRecord value2(String value) {
        setTitle(value);
        return this;
    }

    @Override
    public ContentLayoutRecord value3(String value) {
        setContent(value);
        return this;
    }

    @Override
    public ContentLayoutRecord value4(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public ContentLayoutRecord values(String value1, String value2, String value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ContentLayoutRecord
     */
    public ContentLayoutRecord() {
        super(ContentLayout.CONTENT_LAYOUT);
    }

    /**
     * Create a detached, initialised ContentLayoutRecord
     */
    public ContentLayoutRecord(String contentKey, String title, String content, String description) {
        super(ContentLayout.CONTENT_LAYOUT);

        set(0, contentKey);
        set(1, title);
        set(2, content);
        set(3, description);
    }
}
