/*
 * This file is generated by jOOQ.
 */
package vn.mcare.system.repository.model.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import vn.mcare.system.repository.model.tables.DataList;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DataListRecord extends UpdatableRecordImpl<DataListRecord> implements Record5<Integer, String, String, String, String> {

    private static final long serialVersionUID = -289771568;

    /**
     * Setter for <code>thangvtm_mcare.data_list.id</code>.
     */
    public DataListRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.data_list.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>thangvtm_mcare.data_list.data_key</code>.
     */
    public DataListRecord setDataKey(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.data_list.data_key</code>.
     */
    public String getDataKey() {
        return (String) get(1);
    }

    /**
     * Setter for <code>thangvtm_mcare.data_list.data_value</code>.
     */
    public DataListRecord setDataValue(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.data_list.data_value</code>.
     */
    public String getDataValue() {
        return (String) get(2);
    }

    /**
     * Setter for <code>thangvtm_mcare.data_list.label</code>.
     */
    public DataListRecord setLabel(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.data_list.label</code>.
     */
    public String getLabel() {
        return (String) get(3);
    }

    /**
     * Setter for <code>thangvtm_mcare.data_list.description</code>.
     */
    public DataListRecord setDescription(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.data_list.description</code>.
     */
    public String getDescription() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, String, String, String, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, String, String, String, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return DataList.DATA_LIST.ID;
    }

    @Override
    public Field<String> field2() {
        return DataList.DATA_LIST.DATA_KEY;
    }

    @Override
    public Field<String> field3() {
        return DataList.DATA_LIST.DATA_VALUE;
    }

    @Override
    public Field<String> field4() {
        return DataList.DATA_LIST.LABEL;
    }

    @Override
    public Field<String> field5() {
        return DataList.DATA_LIST.DESCRIPTION;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getDataKey();
    }

    @Override
    public String component3() {
        return getDataValue();
    }

    @Override
    public String component4() {
        return getLabel();
    }

    @Override
    public String component5() {
        return getDescription();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getDataKey();
    }

    @Override
    public String value3() {
        return getDataValue();
    }

    @Override
    public String value4() {
        return getLabel();
    }

    @Override
    public String value5() {
        return getDescription();
    }

    @Override
    public DataListRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public DataListRecord value2(String value) {
        setDataKey(value);
        return this;
    }

    @Override
    public DataListRecord value3(String value) {
        setDataValue(value);
        return this;
    }

    @Override
    public DataListRecord value4(String value) {
        setLabel(value);
        return this;
    }

    @Override
    public DataListRecord value5(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public DataListRecord values(Integer value1, String value2, String value3, String value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DataListRecord
     */
    public DataListRecord() {
        super(DataList.DATA_LIST);
    }

    /**
     * Create a detached, initialised DataListRecord
     */
    public DataListRecord(Integer id, String dataKey, String dataValue, String label, String description) {
        super(DataList.DATA_LIST);

        set(0, id);
        set(1, dataKey);
        set(2, dataValue);
        set(3, label);
        set(4, description);
    }
}
