/*
 * This file is generated by jOOQ.
 */
package vn.mcare.system.repository.model.tables.records;


import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;

import vn.mcare.system.repository.model.tables.Inventory;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InventoryRecord extends UpdatableRecordImpl<InventoryRecord> implements Record9<String, String, String, Integer, Double, Double, Integer, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = -12692899;

    /**
     * Setter for <code>thangvtm_mcare.inventory.inventory_id</code>.
     */
    public InventoryRecord setInventoryId(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.inventory.inventory_id</code>.
     */
    public String getInventoryId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>thangvtm_mcare.inventory.medicine_id</code>.
     */
    public InventoryRecord setMedicineId(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.inventory.medicine_id</code>.
     */
    public String getMedicineId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>thangvtm_mcare.inventory.lot_id</code>.
     */
    public InventoryRecord setLotId(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.inventory.lot_id</code>.
     */
    public String getLotId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>thangvtm_mcare.inventory.amount</code>.
     */
    public InventoryRecord setAmount(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.inventory.amount</code>.
     */
    public Integer getAmount() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>thangvtm_mcare.inventory.import_price</code>.
     */
    public InventoryRecord setImportPrice(Double value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.inventory.import_price</code>.
     */
    public Double getImportPrice() {
        return (Double) get(4);
    }

    /**
     * Setter for <code>thangvtm_mcare.inventory.sell_price</code>.
     */
    public InventoryRecord setSellPrice(Double value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.inventory.sell_price</code>.
     */
    public Double getSellPrice() {
        return (Double) get(5);
    }

    /**
     * Setter for <code>thangvtm_mcare.inventory.cal_unit</code>.
     */
    public InventoryRecord setCalUnit(Integer value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.inventory.cal_unit</code>.
     */
    public Integer getCalUnit() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>thangvtm_mcare.inventory.created_at</code>.
     */
    public InventoryRecord setCreatedAt(LocalDateTime value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.inventory.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>thangvtm_mcare.inventory.modified_at</code>.
     */
    public InventoryRecord setModifiedAt(LocalDateTime value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.inventory.modified_at</code>.
     */
    public LocalDateTime getModifiedAt() {
        return (LocalDateTime) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<String, String, String, Integer, Double, Double, Integer, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<String, String, String, Integer, Double, Double, Integer, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Inventory.INVENTORY.INVENTORY_ID;
    }

    @Override
    public Field<String> field2() {
        return Inventory.INVENTORY.MEDICINE_ID;
    }

    @Override
    public Field<String> field3() {
        return Inventory.INVENTORY.LOT_ID;
    }

    @Override
    public Field<Integer> field4() {
        return Inventory.INVENTORY.AMOUNT;
    }

    @Override
    public Field<Double> field5() {
        return Inventory.INVENTORY.IMPORT_PRICE;
    }

    @Override
    public Field<Double> field6() {
        return Inventory.INVENTORY.SELL_PRICE;
    }

    @Override
    public Field<Integer> field7() {
        return Inventory.INVENTORY.CAL_UNIT;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return Inventory.INVENTORY.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field9() {
        return Inventory.INVENTORY.MODIFIED_AT;
    }

    @Override
    public String component1() {
        return getInventoryId();
    }

    @Override
    public String component2() {
        return getMedicineId();
    }

    @Override
    public String component3() {
        return getLotId();
    }

    @Override
    public Integer component4() {
        return getAmount();
    }

    @Override
    public Double component5() {
        return getImportPrice();
    }

    @Override
    public Double component6() {
        return getSellPrice();
    }

    @Override
    public Integer component7() {
        return getCalUnit();
    }

    @Override
    public LocalDateTime component8() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component9() {
        return getModifiedAt();
    }

    @Override
    public String value1() {
        return getInventoryId();
    }

    @Override
    public String value2() {
        return getMedicineId();
    }

    @Override
    public String value3() {
        return getLotId();
    }

    @Override
    public Integer value4() {
        return getAmount();
    }

    @Override
    public Double value5() {
        return getImportPrice();
    }

    @Override
    public Double value6() {
        return getSellPrice();
    }

    @Override
    public Integer value7() {
        return getCalUnit();
    }

    @Override
    public LocalDateTime value8() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value9() {
        return getModifiedAt();
    }

    @Override
    public InventoryRecord value1(String value) {
        setInventoryId(value);
        return this;
    }

    @Override
    public InventoryRecord value2(String value) {
        setMedicineId(value);
        return this;
    }

    @Override
    public InventoryRecord value3(String value) {
        setLotId(value);
        return this;
    }

    @Override
    public InventoryRecord value4(Integer value) {
        setAmount(value);
        return this;
    }

    @Override
    public InventoryRecord value5(Double value) {
        setImportPrice(value);
        return this;
    }

    @Override
    public InventoryRecord value6(Double value) {
        setSellPrice(value);
        return this;
    }

    @Override
    public InventoryRecord value7(Integer value) {
        setCalUnit(value);
        return this;
    }

    @Override
    public InventoryRecord value8(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public InventoryRecord value9(LocalDateTime value) {
        setModifiedAt(value);
        return this;
    }

    @Override
    public InventoryRecord values(String value1, String value2, String value3, Integer value4, Double value5, Double value6, Integer value7, LocalDateTime value8, LocalDateTime value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached InventoryRecord
     */
    public InventoryRecord() {
        super(Inventory.INVENTORY);
    }

    /**
     * Create a detached, initialised InventoryRecord
     */
    public InventoryRecord(String inventoryId, String medicineId, String lotId, Integer amount, Double importPrice, Double sellPrice, Integer calUnit, LocalDateTime createdAt, LocalDateTime modifiedAt) {
        super(Inventory.INVENTORY);

        set(0, inventoryId);
        set(1, medicineId);
        set(2, lotId);
        set(3, amount);
        set(4, importPrice);
        set(5, sellPrice);
        set(6, calUnit);
        set(7, createdAt);
        set(8, modifiedAt);
    }
}
