/*
 * This file is generated by jOOQ.
 */
package vn.mcare.system.repository.model.tables.records;


import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;

import vn.mcare.system.repository.model.tables.MedicalReportDetail;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MedicalReportDetailRecord extends UpdatableRecordImpl<MedicalReportDetailRecord> implements Record6<Integer, String, String, Integer, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1713250808;

    /**
     * Setter for <code>thangvtm_mcare.medical_report_detail.id</code>.
     */
    public MedicalReportDetailRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.medical_report_detail.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>thangvtm_mcare.medical_report_detail.medical_report_id</code>.
     */
    public MedicalReportDetailRecord setMedicalReportId(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.medical_report_detail.medical_report_id</code>.
     */
    public String getMedicalReportId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>thangvtm_mcare.medical_report_detail.examine_id</code>.
     */
    public MedicalReportDetailRecord setExamineId(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.medical_report_detail.examine_id</code>.
     */
    public String getExamineId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>thangvtm_mcare.medical_report_detail.status</code>.
     */
    public MedicalReportDetailRecord setStatus(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.medical_report_detail.status</code>.
     */
    public Integer getStatus() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>thangvtm_mcare.medical_report_detail.created_at</code>.
     */
    public MedicalReportDetailRecord setCreatedAt(LocalDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.medical_report_detail.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>thangvtm_mcare.medical_report_detail.modified_at</code>.
     */
    public MedicalReportDetailRecord setModifiedAt(LocalDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.medical_report_detail.modified_at</code>.
     */
    public LocalDateTime getModifiedAt() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, String, String, Integer, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Integer, String, String, Integer, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return MedicalReportDetail.MEDICAL_REPORT_DETAIL.ID;
    }

    @Override
    public Field<String> field2() {
        return MedicalReportDetail.MEDICAL_REPORT_DETAIL.MEDICAL_REPORT_ID;
    }

    @Override
    public Field<String> field3() {
        return MedicalReportDetail.MEDICAL_REPORT_DETAIL.EXAMINE_ID;
    }

    @Override
    public Field<Integer> field4() {
        return MedicalReportDetail.MEDICAL_REPORT_DETAIL.STATUS;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return MedicalReportDetail.MEDICAL_REPORT_DETAIL.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return MedicalReportDetail.MEDICAL_REPORT_DETAIL.MODIFIED_AT;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getMedicalReportId();
    }

    @Override
    public String component3() {
        return getExamineId();
    }

    @Override
    public Integer component4() {
        return getStatus();
    }

    @Override
    public LocalDateTime component5() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component6() {
        return getModifiedAt();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getMedicalReportId();
    }

    @Override
    public String value3() {
        return getExamineId();
    }

    @Override
    public Integer value4() {
        return getStatus();
    }

    @Override
    public LocalDateTime value5() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value6() {
        return getModifiedAt();
    }

    @Override
    public MedicalReportDetailRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public MedicalReportDetailRecord value2(String value) {
        setMedicalReportId(value);
        return this;
    }

    @Override
    public MedicalReportDetailRecord value3(String value) {
        setExamineId(value);
        return this;
    }

    @Override
    public MedicalReportDetailRecord value4(Integer value) {
        setStatus(value);
        return this;
    }

    @Override
    public MedicalReportDetailRecord value5(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public MedicalReportDetailRecord value6(LocalDateTime value) {
        setModifiedAt(value);
        return this;
    }

    @Override
    public MedicalReportDetailRecord values(Integer value1, String value2, String value3, Integer value4, LocalDateTime value5, LocalDateTime value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MedicalReportDetailRecord
     */
    public MedicalReportDetailRecord() {
        super(MedicalReportDetail.MEDICAL_REPORT_DETAIL);
    }

    /**
     * Create a detached, initialised MedicalReportDetailRecord
     */
    public MedicalReportDetailRecord(Integer id, String medicalReportId, String examineId, Integer status, LocalDateTime createdAt, LocalDateTime modifiedAt) {
        super(MedicalReportDetail.MEDICAL_REPORT_DETAIL);

        set(0, id);
        set(1, medicalReportId);
        set(2, examineId);
        set(3, status);
        set(4, createdAt);
        set(5, modifiedAt);
    }
}
