/*
 * This file is generated by jOOQ.
 */
package vn.mcare.system.repository.model.tables.records;


import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import vn.mcare.system.repository.model.tables.Medicine;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MedicineRecord extends UpdatableRecordImpl<MedicineRecord> implements Record5<String, String, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1786261039;

    /**
     * Setter for <code>thangvtm_mcare.medicine.medicine_id</code>.
     */
    public MedicineRecord setMedicineId(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.medicine.medicine_id</code>.
     */
    public String getMedicineId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>thangvtm_mcare.medicine.medicine_name</code>.
     */
    public MedicineRecord setMedicineName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.medicine.medicine_name</code>.
     */
    public String getMedicineName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>thangvtm_mcare.medicine.source</code>.
     */
    public MedicineRecord setSource(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.medicine.source</code>.
     */
    public String getSource() {
        return (String) get(2);
    }

    /**
     * Setter for <code>thangvtm_mcare.medicine.created_at</code>.
     */
    public MedicineRecord setCreatedAt(LocalDateTime value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.medicine.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>thangvtm_mcare.medicine.modified_at</code>.
     */
    public MedicineRecord setModifiedAt(LocalDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.medicine.modified_at</code>.
     */
    public LocalDateTime getModifiedAt() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<String, String, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<String, String, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Medicine.MEDICINE.MEDICINE_ID;
    }

    @Override
    public Field<String> field2() {
        return Medicine.MEDICINE.MEDICINE_NAME;
    }

    @Override
    public Field<String> field3() {
        return Medicine.MEDICINE.SOURCE;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return Medicine.MEDICINE.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return Medicine.MEDICINE.MODIFIED_AT;
    }

    @Override
    public String component1() {
        return getMedicineId();
    }

    @Override
    public String component2() {
        return getMedicineName();
    }

    @Override
    public String component3() {
        return getSource();
    }

    @Override
    public LocalDateTime component4() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component5() {
        return getModifiedAt();
    }

    @Override
    public String value1() {
        return getMedicineId();
    }

    @Override
    public String value2() {
        return getMedicineName();
    }

    @Override
    public String value3() {
        return getSource();
    }

    @Override
    public LocalDateTime value4() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value5() {
        return getModifiedAt();
    }

    @Override
    public MedicineRecord value1(String value) {
        setMedicineId(value);
        return this;
    }

    @Override
    public MedicineRecord value2(String value) {
        setMedicineName(value);
        return this;
    }

    @Override
    public MedicineRecord value3(String value) {
        setSource(value);
        return this;
    }

    @Override
    public MedicineRecord value4(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public MedicineRecord value5(LocalDateTime value) {
        setModifiedAt(value);
        return this;
    }

    @Override
    public MedicineRecord values(String value1, String value2, String value3, LocalDateTime value4, LocalDateTime value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MedicineRecord
     */
    public MedicineRecord() {
        super(Medicine.MEDICINE);
    }

    /**
     * Create a detached, initialised MedicineRecord
     */
    public MedicineRecord(String medicineId, String medicineName, String source, LocalDateTime createdAt, LocalDateTime modifiedAt) {
        super(Medicine.MEDICINE);

        set(0, medicineId);
        set(1, medicineName);
        set(2, source);
        set(3, createdAt);
        set(4, modifiedAt);
    }
}
