/*
 * This file is generated by jOOQ.
 */
package vn.mcare.system.repository.model.tables.records;


import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import vn.mcare.system.repository.model.tables.MedicalReport;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MedicalReportRecord extends UpdatableRecordImpl<MedicalReportRecord> implements Record5<String, String, Integer, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = -1576233409;

    /**
     * Setter for <code>thangvtm_mcare.medical_report.medical_report_id</code>.
     */
    public MedicalReportRecord setMedicalReportId(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.medical_report.medical_report_id</code>.
     */
    public String getMedicalReportId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>thangvtm_mcare.medical_report.cif</code>.
     */
    public MedicalReportRecord setCif(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.medical_report.cif</code>.
     */
    public String getCif() {
        return (String) get(1);
    }

    /**
     * Setter for <code>thangvtm_mcare.medical_report.blood_group</code>.
     */
    public MedicalReportRecord setBloodGroup(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.medical_report.blood_group</code>.
     */
    public Integer getBloodGroup() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>thangvtm_mcare.medical_report.created_at</code>.
     */
    public MedicalReportRecord setCreatedAt(LocalDateTime value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.medical_report.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>thangvtm_mcare.medical_report.modified_at</code>.
     */
    public MedicalReportRecord setModifiedAt(LocalDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.medical_report.modified_at</code>.
     */
    public LocalDateTime getModifiedAt() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<String, String, Integer, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<String, String, Integer, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return MedicalReport.MEDICAL_REPORT.MEDICAL_REPORT_ID;
    }

    @Override
    public Field<String> field2() {
        return MedicalReport.MEDICAL_REPORT.CIF;
    }

    @Override
    public Field<Integer> field3() {
        return MedicalReport.MEDICAL_REPORT.BLOOD_GROUP;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return MedicalReport.MEDICAL_REPORT.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return MedicalReport.MEDICAL_REPORT.MODIFIED_AT;
    }

    @Override
    public String component1() {
        return getMedicalReportId();
    }

    @Override
    public String component2() {
        return getCif();
    }

    @Override
    public Integer component3() {
        return getBloodGroup();
    }

    @Override
    public LocalDateTime component4() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component5() {
        return getModifiedAt();
    }

    @Override
    public String value1() {
        return getMedicalReportId();
    }

    @Override
    public String value2() {
        return getCif();
    }

    @Override
    public Integer value3() {
        return getBloodGroup();
    }

    @Override
    public LocalDateTime value4() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value5() {
        return getModifiedAt();
    }

    @Override
    public MedicalReportRecord value1(String value) {
        setMedicalReportId(value);
        return this;
    }

    @Override
    public MedicalReportRecord value2(String value) {
        setCif(value);
        return this;
    }

    @Override
    public MedicalReportRecord value3(Integer value) {
        setBloodGroup(value);
        return this;
    }

    @Override
    public MedicalReportRecord value4(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public MedicalReportRecord value5(LocalDateTime value) {
        setModifiedAt(value);
        return this;
    }

    @Override
    public MedicalReportRecord values(String value1, String value2, Integer value3, LocalDateTime value4, LocalDateTime value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MedicalReportRecord
     */
    public MedicalReportRecord() {
        super(MedicalReport.MEDICAL_REPORT);
    }

    /**
     * Create a detached, initialised MedicalReportRecord
     */
    public MedicalReportRecord(String medicalReportId, String cif, Integer bloodGroup, LocalDateTime createdAt, LocalDateTime modifiedAt) {
        super(MedicalReport.MEDICAL_REPORT);

        set(0, medicalReportId);
        set(1, cif);
        set(2, bloodGroup);
        set(3, createdAt);
        set(4, modifiedAt);
    }
}
