/*
 * This file is generated by jOOQ.
 */
package vn.mcare.system.repository.model.tables.records;


import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;

import vn.mcare.system.repository.model.tables.MedicineBill;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MedicineBillRecord extends UpdatableRecordImpl<MedicineBillRecord> implements Record8<Integer, String, String, String, Integer, Integer, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = -443484201;

    /**
     * Setter for <code>thangvtm_mcare.medicine_bill.id</code>.
     */
    public MedicineBillRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.medicine_bill.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>thangvtm_mcare.medicine_bill.bill_id</code>.
     */
    public MedicineBillRecord setBillId(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.medicine_bill.bill_id</code>.
     */
    public String getBillId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>thangvtm_mcare.medicine_bill.inventory_id</code>.
     */
    public MedicineBillRecord setInventoryId(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.medicine_bill.inventory_id</code>.
     */
    public String getInventoryId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>thangvtm_mcare.medicine_bill.medicine_id</code>.
     */
    public MedicineBillRecord setMedicineId(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.medicine_bill.medicine_id</code>.
     */
    public String getMedicineId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>thangvtm_mcare.medicine_bill.amount</code>.
     */
    public MedicineBillRecord setAmount(Integer value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.medicine_bill.amount</code>.
     */
    public Integer getAmount() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>thangvtm_mcare.medicine_bill.cal_unit</code>.
     */
    public MedicineBillRecord setCalUnit(Integer value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.medicine_bill.cal_unit</code>.
     */
    public Integer getCalUnit() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>thangvtm_mcare.medicine_bill.created_at</code>.
     */
    public MedicineBillRecord setCreatedAt(LocalDateTime value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.medicine_bill.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>thangvtm_mcare.medicine_bill.modified_at</code>.
     */
    public MedicineBillRecord setModifiedAt(LocalDateTime value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.medicine_bill.modified_at</code>.
     */
    public LocalDateTime getModifiedAt() {
        return (LocalDateTime) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Integer, String, String, String, Integer, Integer, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Integer, String, String, String, Integer, Integer, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return MedicineBill.MEDICINE_BILL.ID;
    }

    @Override
    public Field<String> field2() {
        return MedicineBill.MEDICINE_BILL.BILL_ID;
    }

    @Override
    public Field<String> field3() {
        return MedicineBill.MEDICINE_BILL.INVENTORY_ID;
    }

    @Override
    public Field<String> field4() {
        return MedicineBill.MEDICINE_BILL.MEDICINE_ID;
    }

    @Override
    public Field<Integer> field5() {
        return MedicineBill.MEDICINE_BILL.AMOUNT;
    }

    @Override
    public Field<Integer> field6() {
        return MedicineBill.MEDICINE_BILL.CAL_UNIT;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return MedicineBill.MEDICINE_BILL.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return MedicineBill.MEDICINE_BILL.MODIFIED_AT;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getBillId();
    }

    @Override
    public String component3() {
        return getInventoryId();
    }

    @Override
    public String component4() {
        return getMedicineId();
    }

    @Override
    public Integer component5() {
        return getAmount();
    }

    @Override
    public Integer component6() {
        return getCalUnit();
    }

    @Override
    public LocalDateTime component7() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component8() {
        return getModifiedAt();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getBillId();
    }

    @Override
    public String value3() {
        return getInventoryId();
    }

    @Override
    public String value4() {
        return getMedicineId();
    }

    @Override
    public Integer value5() {
        return getAmount();
    }

    @Override
    public Integer value6() {
        return getCalUnit();
    }

    @Override
    public LocalDateTime value7() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value8() {
        return getModifiedAt();
    }

    @Override
    public MedicineBillRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public MedicineBillRecord value2(String value) {
        setBillId(value);
        return this;
    }

    @Override
    public MedicineBillRecord value3(String value) {
        setInventoryId(value);
        return this;
    }

    @Override
    public MedicineBillRecord value4(String value) {
        setMedicineId(value);
        return this;
    }

    @Override
    public MedicineBillRecord value5(Integer value) {
        setAmount(value);
        return this;
    }

    @Override
    public MedicineBillRecord value6(Integer value) {
        setCalUnit(value);
        return this;
    }

    @Override
    public MedicineBillRecord value7(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public MedicineBillRecord value8(LocalDateTime value) {
        setModifiedAt(value);
        return this;
    }

    @Override
    public MedicineBillRecord values(Integer value1, String value2, String value3, String value4, Integer value5, Integer value6, LocalDateTime value7, LocalDateTime value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MedicineBillRecord
     */
    public MedicineBillRecord() {
        super(MedicineBill.MEDICINE_BILL);
    }

    /**
     * Create a detached, initialised MedicineBillRecord
     */
    public MedicineBillRecord(Integer id, String billId, String inventoryId, String medicineId, Integer amount, Integer calUnit, LocalDateTime createdAt, LocalDateTime modifiedAt) {
        super(MedicineBill.MEDICINE_BILL);

        set(0, id);
        set(1, billId);
        set(2, inventoryId);
        set(3, medicineId);
        set(4, amount);
        set(5, calUnit);
        set(6, createdAt);
        set(7, modifiedAt);
    }
}
