/*
 * This file is generated by jOOQ.
 */
package vn.mcare.system.repository.model.tables.records;


import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;

import vn.mcare.system.repository.model.tables.Prescription;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PrescriptionRecord extends UpdatableRecordImpl<PrescriptionRecord> implements Record8<Integer, String, String, Integer, Integer, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = -1305461260;

    /**
     * Setter for <code>thangvtm_mcare.prescription.id</code>.
     */
    public PrescriptionRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.prescription.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>thangvtm_mcare.prescription.examine_id</code>.
     */
    public PrescriptionRecord setExamineId(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.prescription.examine_id</code>.
     */
    public String getExamineId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>thangvtm_mcare.prescription.medicine_id</code>.
     */
    public PrescriptionRecord setMedicineId(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.prescription.medicine_id</code>.
     */
    public String getMedicineId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>thangvtm_mcare.prescription.amount</code>.
     */
    public PrescriptionRecord setAmount(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.prescription.amount</code>.
     */
    public Integer getAmount() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>thangvtm_mcare.prescription.cal_unit</code>.
     */
    public PrescriptionRecord setCalUnit(Integer value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.prescription.cal_unit</code>.
     */
    public Integer getCalUnit() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>thangvtm_mcare.prescription.description</code>.
     */
    public PrescriptionRecord setDescription(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.prescription.description</code>.
     */
    public String getDescription() {
        return (String) get(5);
    }

    /**
     * Setter for <code>thangvtm_mcare.prescription.created_at</code>.
     */
    public PrescriptionRecord setCreatedAt(LocalDateTime value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.prescription.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>thangvtm_mcare.prescription.modified_at</code>.
     */
    public PrescriptionRecord setModifiedAt(LocalDateTime value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.prescription.modified_at</code>.
     */
    public LocalDateTime getModifiedAt() {
        return (LocalDateTime) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Integer, String, String, Integer, Integer, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Integer, String, String, Integer, Integer, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Prescription.PRESCRIPTION.ID;
    }

    @Override
    public Field<String> field2() {
        return Prescription.PRESCRIPTION.EXAMINE_ID;
    }

    @Override
    public Field<String> field3() {
        return Prescription.PRESCRIPTION.MEDICINE_ID;
    }

    @Override
    public Field<Integer> field4() {
        return Prescription.PRESCRIPTION.AMOUNT;
    }

    @Override
    public Field<Integer> field5() {
        return Prescription.PRESCRIPTION.CAL_UNIT;
    }

    @Override
    public Field<String> field6() {
        return Prescription.PRESCRIPTION.DESCRIPTION;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return Prescription.PRESCRIPTION.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return Prescription.PRESCRIPTION.MODIFIED_AT;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getExamineId();
    }

    @Override
    public String component3() {
        return getMedicineId();
    }

    @Override
    public Integer component4() {
        return getAmount();
    }

    @Override
    public Integer component5() {
        return getCalUnit();
    }

    @Override
    public String component6() {
        return getDescription();
    }

    @Override
    public LocalDateTime component7() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component8() {
        return getModifiedAt();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getExamineId();
    }

    @Override
    public String value3() {
        return getMedicineId();
    }

    @Override
    public Integer value4() {
        return getAmount();
    }

    @Override
    public Integer value5() {
        return getCalUnit();
    }

    @Override
    public String value6() {
        return getDescription();
    }

    @Override
    public LocalDateTime value7() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value8() {
        return getModifiedAt();
    }

    @Override
    public PrescriptionRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public PrescriptionRecord value2(String value) {
        setExamineId(value);
        return this;
    }

    @Override
    public PrescriptionRecord value3(String value) {
        setMedicineId(value);
        return this;
    }

    @Override
    public PrescriptionRecord value4(Integer value) {
        setAmount(value);
        return this;
    }

    @Override
    public PrescriptionRecord value5(Integer value) {
        setCalUnit(value);
        return this;
    }

    @Override
    public PrescriptionRecord value6(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public PrescriptionRecord value7(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public PrescriptionRecord value8(LocalDateTime value) {
        setModifiedAt(value);
        return this;
    }

    @Override
    public PrescriptionRecord values(Integer value1, String value2, String value3, Integer value4, Integer value5, String value6, LocalDateTime value7, LocalDateTime value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PrescriptionRecord
     */
    public PrescriptionRecord() {
        super(Prescription.PRESCRIPTION);
    }

    /**
     * Create a detached, initialised PrescriptionRecord
     */
    public PrescriptionRecord(Integer id, String examineId, String medicineId, Integer amount, Integer calUnit, String description, LocalDateTime createdAt, LocalDateTime modifiedAt) {
        super(Prescription.PRESCRIPTION);

        set(0, id);
        set(1, examineId);
        set(2, medicineId);
        set(3, amount);
        set(4, calUnit);
        set(5, description);
        set(6, createdAt);
        set(7, modifiedAt);
    }
}
