/*
 * This file is generated by jOOQ.
 */
package vn.mcare.system.repository.model.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import vn.mcare.system.repository.model.tables.Province;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProvinceRecord extends UpdatableRecordImpl<ProvinceRecord> implements Record3<Integer, String, String> {

    private static final long serialVersionUID = 611209313;

    /**
     * Setter for <code>thangvtm_mcare.province.id</code>.
     */
    public ProvinceRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.province.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>thangvtm_mcare.province.name</code>.
     */
    public ProvinceRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.province.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>thangvtm_mcare.province.code</code>.
     */
    public ProvinceRecord setCode(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.province.code</code>.
     */
    public String getCode() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Province.PROVINCE.ID;
    }

    @Override
    public Field<String> field2() {
        return Province.PROVINCE.NAME;
    }

    @Override
    public Field<String> field3() {
        return Province.PROVINCE.CODE;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getCode();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getCode();
    }

    @Override
    public ProvinceRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public ProvinceRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public ProvinceRecord value3(String value) {
        setCode(value);
        return this;
    }

    @Override
    public ProvinceRecord values(Integer value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProvinceRecord
     */
    public ProvinceRecord() {
        super(Province.PROVINCE);
    }

    /**
     * Create a detached, initialised ProvinceRecord
     */
    public ProvinceRecord(Integer id, String name, String code) {
        super(Province.PROVINCE);

        set(0, id);
        set(1, name);
        set(2, code);
    }
}
