/*
 * This file is generated by jOOQ.
 */
package vn.mcare.system.repository.model.tables.records;


import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;

import vn.mcare.system.repository.model.tables.RegisterExamination;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RegisterExaminationRecord extends UpdatableRecordImpl<RegisterExaminationRecord> implements Record10<Integer, String, String, Integer, String, String, LocalDateTime, LocalDateTime, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = -1451784802;

    /**
     * Setter for <code>thangvtm_mcare.register_examination.id</code>.
     */
    public RegisterExaminationRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.register_examination.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>thangvtm_mcare.register_examination.random_number</code>.
     */
    public RegisterExaminationRecord setRandomNumber(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.register_examination.random_number</code>.
     */
    public String getRandomNumber() {
        return (String) get(1);
    }

    /**
     * Setter for <code>thangvtm_mcare.register_examination.full_name</code>.
     */
    public RegisterExaminationRecord setFullName(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.register_examination.full_name</code>.
     */
    public String getFullName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>thangvtm_mcare.register_examination.status</code>.
     */
    public RegisterExaminationRecord setStatus(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.register_examination.status</code>.
     */
    public Integer getStatus() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>thangvtm_mcare.register_examination.email</code>.
     */
    public RegisterExaminationRecord setEmail(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.register_examination.email</code>.
     */
    public String getEmail() {
        return (String) get(4);
    }

    /**
     * Setter for <code>thangvtm_mcare.register_examination.phone</code>.
     */
    public RegisterExaminationRecord setPhone(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.register_examination.phone</code>.
     */
    public String getPhone() {
        return (String) get(5);
    }

    /**
     * Setter for <code>thangvtm_mcare.register_examination.from_date</code>.
     */
    public RegisterExaminationRecord setFromDate(LocalDateTime value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.register_examination.from_date</code>.
     */
    public LocalDateTime getFromDate() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>thangvtm_mcare.register_examination.to_date</code>.
     */
    public RegisterExaminationRecord setToDate(LocalDateTime value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.register_examination.to_date</code>.
     */
    public LocalDateTime getToDate() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>thangvtm_mcare.register_examination.created_at</code>.
     */
    public RegisterExaminationRecord setCreatedAt(LocalDateTime value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.register_examination.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>thangvtm_mcare.register_examination.modified_at</code>.
     */
    public RegisterExaminationRecord setModifiedAt(LocalDateTime value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.register_examination.modified_at</code>.
     */
    public LocalDateTime getModifiedAt() {
        return (LocalDateTime) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<Integer, String, String, Integer, String, String, LocalDateTime, LocalDateTime, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<Integer, String, String, Integer, String, String, LocalDateTime, LocalDateTime, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return RegisterExamination.REGISTER_EXAMINATION.ID;
    }

    @Override
    public Field<String> field2() {
        return RegisterExamination.REGISTER_EXAMINATION.RANDOM_NUMBER;
    }

    @Override
    public Field<String> field3() {
        return RegisterExamination.REGISTER_EXAMINATION.FULL_NAME;
    }

    @Override
    public Field<Integer> field4() {
        return RegisterExamination.REGISTER_EXAMINATION.STATUS;
    }

    @Override
    public Field<String> field5() {
        return RegisterExamination.REGISTER_EXAMINATION.EMAIL;
    }

    @Override
    public Field<String> field6() {
        return RegisterExamination.REGISTER_EXAMINATION.PHONE;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return RegisterExamination.REGISTER_EXAMINATION.FROM_DATE;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return RegisterExamination.REGISTER_EXAMINATION.TO_DATE;
    }

    @Override
    public Field<LocalDateTime> field9() {
        return RegisterExamination.REGISTER_EXAMINATION.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field10() {
        return RegisterExamination.REGISTER_EXAMINATION.MODIFIED_AT;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getRandomNumber();
    }

    @Override
    public String component3() {
        return getFullName();
    }

    @Override
    public Integer component4() {
        return getStatus();
    }

    @Override
    public String component5() {
        return getEmail();
    }

    @Override
    public String component6() {
        return getPhone();
    }

    @Override
    public LocalDateTime component7() {
        return getFromDate();
    }

    @Override
    public LocalDateTime component8() {
        return getToDate();
    }

    @Override
    public LocalDateTime component9() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component10() {
        return getModifiedAt();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getRandomNumber();
    }

    @Override
    public String value3() {
        return getFullName();
    }

    @Override
    public Integer value4() {
        return getStatus();
    }

    @Override
    public String value5() {
        return getEmail();
    }

    @Override
    public String value6() {
        return getPhone();
    }

    @Override
    public LocalDateTime value7() {
        return getFromDate();
    }

    @Override
    public LocalDateTime value8() {
        return getToDate();
    }

    @Override
    public LocalDateTime value9() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value10() {
        return getModifiedAt();
    }

    @Override
    public RegisterExaminationRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public RegisterExaminationRecord value2(String value) {
        setRandomNumber(value);
        return this;
    }

    @Override
    public RegisterExaminationRecord value3(String value) {
        setFullName(value);
        return this;
    }

    @Override
    public RegisterExaminationRecord value4(Integer value) {
        setStatus(value);
        return this;
    }

    @Override
    public RegisterExaminationRecord value5(String value) {
        setEmail(value);
        return this;
    }

    @Override
    public RegisterExaminationRecord value6(String value) {
        setPhone(value);
        return this;
    }

    @Override
    public RegisterExaminationRecord value7(LocalDateTime value) {
        setFromDate(value);
        return this;
    }

    @Override
    public RegisterExaminationRecord value8(LocalDateTime value) {
        setToDate(value);
        return this;
    }

    @Override
    public RegisterExaminationRecord value9(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public RegisterExaminationRecord value10(LocalDateTime value) {
        setModifiedAt(value);
        return this;
    }

    @Override
    public RegisterExaminationRecord values(Integer value1, String value2, String value3, Integer value4, String value5, String value6, LocalDateTime value7, LocalDateTime value8, LocalDateTime value9, LocalDateTime value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RegisterExaminationRecord
     */
    public RegisterExaminationRecord() {
        super(RegisterExamination.REGISTER_EXAMINATION);
    }

    /**
     * Create a detached, initialised RegisterExaminationRecord
     */
    public RegisterExaminationRecord(Integer id, String randomNumber, String fullName, Integer status, String email, String phone, LocalDateTime fromDate, LocalDateTime toDate, LocalDateTime createdAt, LocalDateTime modifiedAt) {
        super(RegisterExamination.REGISTER_EXAMINATION);

        set(0, id);
        set(1, randomNumber);
        set(2, fullName);
        set(3, status);
        set(4, email);
        set(5, phone);
        set(6, fromDate);
        set(7, toDate);
        set(8, createdAt);
        set(9, modifiedAt);
    }
}
