/*
 * This file is generated by jOOQ.
 */
package vn.mcare.system.repository.model.tables.records;


import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;

import vn.mcare.system.repository.model.tables.Service;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ServiceRecord extends UpdatableRecordImpl<ServiceRecord> implements Record6<String, String, Double, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 193399732;

    /**
     * Setter for <code>thangvtm_mcare.service.service_id</code>.
     */
    public ServiceRecord setServiceId(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.service.service_id</code>.
     */
    public String getServiceId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>thangvtm_mcare.service.service_name</code>.
     */
    public ServiceRecord setServiceName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.service.service_name</code>.
     */
    public String getServiceName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>thangvtm_mcare.service.price</code>.
     */
    public ServiceRecord setPrice(Double value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.service.price</code>.
     */
    public Double getPrice() {
        return (Double) get(2);
    }

    /**
     * Setter for <code>thangvtm_mcare.service.description</code>.
     */
    public ServiceRecord setDescription(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.service.description</code>.
     */
    public String getDescription() {
        return (String) get(3);
    }

    /**
     * Setter for <code>thangvtm_mcare.service.created_at</code>.
     */
    public ServiceRecord setCreatedAt(LocalDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.service.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>thangvtm_mcare.service.modified_at</code>.
     */
    public ServiceRecord setModifiedAt(LocalDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.service.modified_at</code>.
     */
    public LocalDateTime getModifiedAt() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<String, String, Double, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<String, String, Double, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Service.SERVICE.SERVICE_ID;
    }

    @Override
    public Field<String> field2() {
        return Service.SERVICE.SERVICE_NAME;
    }

    @Override
    public Field<Double> field3() {
        return Service.SERVICE.PRICE;
    }

    @Override
    public Field<String> field4() {
        return Service.SERVICE.DESCRIPTION;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return Service.SERVICE.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return Service.SERVICE.MODIFIED_AT;
    }

    @Override
    public String component1() {
        return getServiceId();
    }

    @Override
    public String component2() {
        return getServiceName();
    }

    @Override
    public Double component3() {
        return getPrice();
    }

    @Override
    public String component4() {
        return getDescription();
    }

    @Override
    public LocalDateTime component5() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component6() {
        return getModifiedAt();
    }

    @Override
    public String value1() {
        return getServiceId();
    }

    @Override
    public String value2() {
        return getServiceName();
    }

    @Override
    public Double value3() {
        return getPrice();
    }

    @Override
    public String value4() {
        return getDescription();
    }

    @Override
    public LocalDateTime value5() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value6() {
        return getModifiedAt();
    }

    @Override
    public ServiceRecord value1(String value) {
        setServiceId(value);
        return this;
    }

    @Override
    public ServiceRecord value2(String value) {
        setServiceName(value);
        return this;
    }

    @Override
    public ServiceRecord value3(Double value) {
        setPrice(value);
        return this;
    }

    @Override
    public ServiceRecord value4(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public ServiceRecord value5(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public ServiceRecord value6(LocalDateTime value) {
        setModifiedAt(value);
        return this;
    }

    @Override
    public ServiceRecord values(String value1, String value2, Double value3, String value4, LocalDateTime value5, LocalDateTime value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ServiceRecord
     */
    public ServiceRecord() {
        super(Service.SERVICE);
    }

    /**
     * Create a detached, initialised ServiceRecord
     */
    public ServiceRecord(String serviceId, String serviceName, Double price, String description, LocalDateTime createdAt, LocalDateTime modifiedAt) {
        super(Service.SERVICE);

        set(0, serviceId);
        set(1, serviceName);
        set(2, price);
        set(3, description);
        set(4, createdAt);
        set(5, modifiedAt);
    }
}
