/*
 * This file is generated by jOOQ.
 */
package vn.mcare.system.repository.model.tables.records;


import java.time.LocalDate;
import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;

import vn.mcare.system.repository.model.tables.ServiceBill;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ServiceBillRecord extends UpdatableRecordImpl<ServiceBillRecord> implements Record8<Integer, String, String, LocalDate, LocalDate, Integer, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = -675796761;

    /**
     * Setter for <code>thangvtm_mcare.service_bill.id</code>.
     */
    public ServiceBillRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.service_bill.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>thangvtm_mcare.service_bill.bill_id</code>.
     */
    public ServiceBillRecord setBillId(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.service_bill.bill_id</code>.
     */
    public String getBillId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>thangvtm_mcare.service_bill.service_id</code>.
     */
    public ServiceBillRecord setServiceId(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.service_bill.service_id</code>.
     */
    public String getServiceId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>thangvtm_mcare.service_bill.from_date</code>.
     */
    public ServiceBillRecord setFromDate(LocalDate value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.service_bill.from_date</code>.
     */
    public LocalDate getFromDate() {
        return (LocalDate) get(3);
    }

    /**
     * Setter for <code>thangvtm_mcare.service_bill.to_date</code>.
     */
    public ServiceBillRecord setToDate(LocalDate value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.service_bill.to_date</code>.
     */
    public LocalDate getToDate() {
        return (LocalDate) get(4);
    }

    /**
     * Setter for <code>thangvtm_mcare.service_bill.quantity</code>.
     */
    public ServiceBillRecord setQuantity(Integer value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.service_bill.quantity</code>.
     */
    public Integer getQuantity() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>thangvtm_mcare.service_bill.created_at</code>.
     */
    public ServiceBillRecord setCreatedAt(LocalDateTime value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.service_bill.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>thangvtm_mcare.service_bill.modified_at</code>.
     */
    public ServiceBillRecord setModifiedAt(LocalDateTime value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.service_bill.modified_at</code>.
     */
    public LocalDateTime getModifiedAt() {
        return (LocalDateTime) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Integer, String, String, LocalDate, LocalDate, Integer, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Integer, String, String, LocalDate, LocalDate, Integer, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return ServiceBill.SERVICE_BILL.ID;
    }

    @Override
    public Field<String> field2() {
        return ServiceBill.SERVICE_BILL.BILL_ID;
    }

    @Override
    public Field<String> field3() {
        return ServiceBill.SERVICE_BILL.SERVICE_ID;
    }

    @Override
    public Field<LocalDate> field4() {
        return ServiceBill.SERVICE_BILL.FROM_DATE;
    }

    @Override
    public Field<LocalDate> field5() {
        return ServiceBill.SERVICE_BILL.TO_DATE;
    }

    @Override
    public Field<Integer> field6() {
        return ServiceBill.SERVICE_BILL.QUANTITY;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return ServiceBill.SERVICE_BILL.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return ServiceBill.SERVICE_BILL.MODIFIED_AT;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getBillId();
    }

    @Override
    public String component3() {
        return getServiceId();
    }

    @Override
    public LocalDate component4() {
        return getFromDate();
    }

    @Override
    public LocalDate component5() {
        return getToDate();
    }

    @Override
    public Integer component6() {
        return getQuantity();
    }

    @Override
    public LocalDateTime component7() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component8() {
        return getModifiedAt();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getBillId();
    }

    @Override
    public String value3() {
        return getServiceId();
    }

    @Override
    public LocalDate value4() {
        return getFromDate();
    }

    @Override
    public LocalDate value5() {
        return getToDate();
    }

    @Override
    public Integer value6() {
        return getQuantity();
    }

    @Override
    public LocalDateTime value7() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value8() {
        return getModifiedAt();
    }

    @Override
    public ServiceBillRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public ServiceBillRecord value2(String value) {
        setBillId(value);
        return this;
    }

    @Override
    public ServiceBillRecord value3(String value) {
        setServiceId(value);
        return this;
    }

    @Override
    public ServiceBillRecord value4(LocalDate value) {
        setFromDate(value);
        return this;
    }

    @Override
    public ServiceBillRecord value5(LocalDate value) {
        setToDate(value);
        return this;
    }

    @Override
    public ServiceBillRecord value6(Integer value) {
        setQuantity(value);
        return this;
    }

    @Override
    public ServiceBillRecord value7(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public ServiceBillRecord value8(LocalDateTime value) {
        setModifiedAt(value);
        return this;
    }

    @Override
    public ServiceBillRecord values(Integer value1, String value2, String value3, LocalDate value4, LocalDate value5, Integer value6, LocalDateTime value7, LocalDateTime value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ServiceBillRecord
     */
    public ServiceBillRecord() {
        super(ServiceBill.SERVICE_BILL);
    }

    /**
     * Create a detached, initialised ServiceBillRecord
     */
    public ServiceBillRecord(Integer id, String billId, String serviceId, LocalDate fromDate, LocalDate toDate, Integer quantity, LocalDateTime createdAt, LocalDateTime modifiedAt) {
        super(ServiceBill.SERVICE_BILL);

        set(0, id);
        set(1, billId);
        set(2, serviceId);
        set(3, fromDate);
        set(4, toDate);
        set(5, quantity);
        set(6, createdAt);
        set(7, modifiedAt);
    }
}
