/*
 * This file is generated by jOOQ.
 */
package vn.mcare.system.repository.model.tables.records;


import java.time.LocalDate;
import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record14;
import org.jooq.Row14;
import org.jooq.impl.UpdatableRecordImpl;

import vn.mcare.system.repository.model.tables.User;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserRecord extends UpdatableRecordImpl<UserRecord> implements Record14<String, String, String, String, String, Integer, LocalDate, String, String, Integer, String, LocalDateTime, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = -161416654;

    /**
     * Setter for <code>thangvtm_mcare.user.cif</code>.
     */
    public UserRecord setCif(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.user.cif</code>.
     */
    public String getCif() {
        return (String) get(0);
    }

    /**
     * Setter for <code>thangvtm_mcare.user.email</code>.
     */
    public UserRecord setEmail(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.user.email</code>.
     */
    public String getEmail() {
        return (String) get(1);
    }

    /**
     * Setter for <code>thangvtm_mcare.user.password</code>.
     */
    public UserRecord setPassword(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.user.password</code>.
     */
    public String getPassword() {
        return (String) get(2);
    }

    /**
     * Setter for <code>thangvtm_mcare.user.salt</code>.
     */
    public UserRecord setSalt(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.user.salt</code>.
     */
    public String getSalt() {
        return (String) get(3);
    }

    /**
     * Setter for <code>thangvtm_mcare.user.full_name</code>.
     */
    public UserRecord setFullName(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.user.full_name</code>.
     */
    public String getFullName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>thangvtm_mcare.user.gender</code>.
     */
    public UserRecord setGender(Integer value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.user.gender</code>.
     */
    public Integer getGender() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>thangvtm_mcare.user.bod</code>.
     */
    public UserRecord setBod(LocalDate value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.user.bod</code>.
     */
    public LocalDate getBod() {
        return (LocalDate) get(6);
    }

    /**
     * Setter for <code>thangvtm_mcare.user.address</code>.
     */
    public UserRecord setAddress(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.user.address</code>.
     */
    public String getAddress() {
        return (String) get(7);
    }

    /**
     * Setter for <code>thangvtm_mcare.user.card_id</code>.
     */
    public UserRecord setCardId(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.user.card_id</code>.
     */
    public String getCardId() {
        return (String) get(8);
    }

    /**
     * Setter for <code>thangvtm_mcare.user.role</code>.
     */
    public UserRecord setRole(Integer value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.user.role</code>.
     */
    public Integer getRole() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>thangvtm_mcare.user.description</code>.
     */
    public UserRecord setDescription(String value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.user.description</code>.
     */
    public String getDescription() {
        return (String) get(10);
    }

    /**
     * Setter for <code>thangvtm_mcare.user.last_login</code>.
     */
    public UserRecord setLastLogin(LocalDateTime value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.user.last_login</code>.
     */
    public LocalDateTime getLastLogin() {
        return (LocalDateTime) get(11);
    }

    /**
     * Setter for <code>thangvtm_mcare.user.created_at</code>.
     */
    public UserRecord setCreatedAt(LocalDateTime value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.user.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(12);
    }

    /**
     * Setter for <code>thangvtm_mcare.user.modified_at</code>.
     */
    public UserRecord setModifiedAt(LocalDateTime value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.user.modified_at</code>.
     */
    public LocalDateTime getModifiedAt() {
        return (LocalDateTime) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record14 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row14<String, String, String, String, String, Integer, LocalDate, String, String, Integer, String, LocalDateTime, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row14) super.fieldsRow();
    }

    @Override
    public Row14<String, String, String, String, String, Integer, LocalDate, String, String, Integer, String, LocalDateTime, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row14) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return User.USER.CIF;
    }

    @Override
    public Field<String> field2() {
        return User.USER.EMAIL;
    }

    @Override
    public Field<String> field3() {
        return User.USER.PASSWORD;
    }

    @Override
    public Field<String> field4() {
        return User.USER.SALT;
    }

    @Override
    public Field<String> field5() {
        return User.USER.FULL_NAME;
    }

    @Override
    public Field<Integer> field6() {
        return User.USER.GENDER;
    }

    @Override
    public Field<LocalDate> field7() {
        return User.USER.BOD;
    }

    @Override
    public Field<String> field8() {
        return User.USER.ADDRESS;
    }

    @Override
    public Field<String> field9() {
        return User.USER.CARD_ID;
    }

    @Override
    public Field<Integer> field10() {
        return User.USER.ROLE;
    }

    @Override
    public Field<String> field11() {
        return User.USER.DESCRIPTION;
    }

    @Override
    public Field<LocalDateTime> field12() {
        return User.USER.LAST_LOGIN;
    }

    @Override
    public Field<LocalDateTime> field13() {
        return User.USER.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field14() {
        return User.USER.MODIFIED_AT;
    }

    @Override
    public String component1() {
        return getCif();
    }

    @Override
    public String component2() {
        return getEmail();
    }

    @Override
    public String component3() {
        return getPassword();
    }

    @Override
    public String component4() {
        return getSalt();
    }

    @Override
    public String component5() {
        return getFullName();
    }

    @Override
    public Integer component6() {
        return getGender();
    }

    @Override
    public LocalDate component7() {
        return getBod();
    }

    @Override
    public String component8() {
        return getAddress();
    }

    @Override
    public String component9() {
        return getCardId();
    }

    @Override
    public Integer component10() {
        return getRole();
    }

    @Override
    public String component11() {
        return getDescription();
    }

    @Override
    public LocalDateTime component12() {
        return getLastLogin();
    }

    @Override
    public LocalDateTime component13() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component14() {
        return getModifiedAt();
    }

    @Override
    public String value1() {
        return getCif();
    }

    @Override
    public String value2() {
        return getEmail();
    }

    @Override
    public String value3() {
        return getPassword();
    }

    @Override
    public String value4() {
        return getSalt();
    }

    @Override
    public String value5() {
        return getFullName();
    }

    @Override
    public Integer value6() {
        return getGender();
    }

    @Override
    public LocalDate value7() {
        return getBod();
    }

    @Override
    public String value8() {
        return getAddress();
    }

    @Override
    public String value9() {
        return getCardId();
    }

    @Override
    public Integer value10() {
        return getRole();
    }

    @Override
    public String value11() {
        return getDescription();
    }

    @Override
    public LocalDateTime value12() {
        return getLastLogin();
    }

    @Override
    public LocalDateTime value13() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value14() {
        return getModifiedAt();
    }

    @Override
    public UserRecord value1(String value) {
        setCif(value);
        return this;
    }

    @Override
    public UserRecord value2(String value) {
        setEmail(value);
        return this;
    }

    @Override
    public UserRecord value3(String value) {
        setPassword(value);
        return this;
    }

    @Override
    public UserRecord value4(String value) {
        setSalt(value);
        return this;
    }

    @Override
    public UserRecord value5(String value) {
        setFullName(value);
        return this;
    }

    @Override
    public UserRecord value6(Integer value) {
        setGender(value);
        return this;
    }

    @Override
    public UserRecord value7(LocalDate value) {
        setBod(value);
        return this;
    }

    @Override
    public UserRecord value8(String value) {
        setAddress(value);
        return this;
    }

    @Override
    public UserRecord value9(String value) {
        setCardId(value);
        return this;
    }

    @Override
    public UserRecord value10(Integer value) {
        setRole(value);
        return this;
    }

    @Override
    public UserRecord value11(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public UserRecord value12(LocalDateTime value) {
        setLastLogin(value);
        return this;
    }

    @Override
    public UserRecord value13(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public UserRecord value14(LocalDateTime value) {
        setModifiedAt(value);
        return this;
    }

    @Override
    public UserRecord values(String value1, String value2, String value3, String value4, String value5, Integer value6, LocalDate value7, String value8, String value9, Integer value10, String value11, LocalDateTime value12, LocalDateTime value13, LocalDateTime value14) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserRecord
     */
    public UserRecord() {
        super(User.USER);
    }

    /**
     * Create a detached, initialised UserRecord
     */
    public UserRecord(String cif, String email, String password, String salt, String fullName, Integer gender, LocalDate bod, String address, String cardId, Integer role, String description, LocalDateTime lastLogin, LocalDateTime createdAt, LocalDateTime modifiedAt) {
        super(User.USER);

        set(0, cif);
        set(1, email);
        set(2, password);
        set(3, salt);
        set(4, fullName);
        set(5, gender);
        set(6, bod);
        set(7, address);
        set(8, cardId);
        set(9, role);
        set(10, description);
        set(11, lastLogin);
        set(12, createdAt);
        set(13, modifiedAt);
    }
}
