/*
 * This file is generated by jOOQ.
 */
package vn.mcare.system.repository.model.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;

import vn.mcare.system.repository.model.tables.Ward;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WardRecord extends UpdatableRecordImpl<WardRecord> implements Record4<Integer, String, String, Integer> {

    private static final long serialVersionUID = 303867455;

    /**
     * Setter for <code>thangvtm_mcare.ward.id</code>.
     */
    public WardRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.ward.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>thangvtm_mcare.ward.name</code>.
     */
    public WardRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.ward.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>thangvtm_mcare.ward.prefix</code>.
     */
    public WardRecord setPrefix(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.ward.prefix</code>.
     */
    public String getPrefix() {
        return (String) get(2);
    }

    /**
     * Setter for <code>thangvtm_mcare.ward.district_id</code>.
     */
    public WardRecord setDistrictId(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>thangvtm_mcare.ward.district_id</code>.
     */
    public Integer getDistrictId() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, String, String, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, String, String, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Ward.WARD.ID;
    }

    @Override
    public Field<String> field2() {
        return Ward.WARD.NAME;
    }

    @Override
    public Field<String> field3() {
        return Ward.WARD.PREFIX;
    }

    @Override
    public Field<Integer> field4() {
        return Ward.WARD.DISTRICT_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getPrefix();
    }

    @Override
    public Integer component4() {
        return getDistrictId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getPrefix();
    }

    @Override
    public Integer value4() {
        return getDistrictId();
    }

    @Override
    public WardRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public WardRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public WardRecord value3(String value) {
        setPrefix(value);
        return this;
    }

    @Override
    public WardRecord value4(Integer value) {
        setDistrictId(value);
        return this;
    }

    @Override
    public WardRecord values(Integer value1, String value2, String value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WardRecord
     */
    public WardRecord() {
        super(Ward.WARD);
    }

    /**
     * Create a detached, initialised WardRecord
     */
    public WardRecord(Integer id, String name, String prefix, Integer districtId) {
        super(Ward.WARD);

        set(0, id);
        set(1, name);
        set(2, prefix);
        set(3, districtId);
    }
}
