/*
 * This file is generated by jOOQ.
 */
package vn.mcare.system.repository.model.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row5;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import vn.mcare.system.repository.model.Keys;
import vn.mcare.system.repository.model.ThangvtmMcare;
import vn.mcare.system.repository.model.tables.records.MedicineRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Medicine extends TableImpl<MedicineRecord> {

    private static final long serialVersionUID = 989994403;

    /**
     * The reference instance of <code>thangvtm_mcare.medicine</code>
     */
    public static final Medicine MEDICINE = new Medicine();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MedicineRecord> getRecordType() {
        return MedicineRecord.class;
    }

    /**
     * The column <code>thangvtm_mcare.medicine.medicine_id</code>.
     */
    public final TableField<MedicineRecord, String> MEDICINE_ID = createField(DSL.name("medicine_id"), org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>thangvtm_mcare.medicine.medicine_name</code>.
     */
    public final TableField<MedicineRecord, String> MEDICINE_NAME = createField(DSL.name("medicine_name"), org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>thangvtm_mcare.medicine.source</code>.
     */
    public final TableField<MedicineRecord, String> SOURCE = createField(DSL.name("source"), org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>thangvtm_mcare.medicine.created_at</code>.
     */
    public final TableField<MedicineRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), org.jooq.impl.SQLDataType.LOCALDATETIME.defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>thangvtm_mcare.medicine.modified_at</code>.
     */
    public final TableField<MedicineRecord, LocalDateTime> MODIFIED_AT = createField(DSL.name("modified_at"), org.jooq.impl.SQLDataType.LOCALDATETIME.defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "");

    /**
     * Create a <code>thangvtm_mcare.medicine</code> table reference
     */
    public Medicine() {
        this(DSL.name("medicine"), null);
    }

    /**
     * Create an aliased <code>thangvtm_mcare.medicine</code> table reference
     */
    public Medicine(String alias) {
        this(DSL.name(alias), MEDICINE);
    }

    /**
     * Create an aliased <code>thangvtm_mcare.medicine</code> table reference
     */
    public Medicine(Name alias) {
        this(alias, MEDICINE);
    }

    private Medicine(Name alias, Table<MedicineRecord> aliased) {
        this(alias, aliased, null);
    }

    private Medicine(Name alias, Table<MedicineRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> Medicine(Table<O> child, ForeignKey<O, MedicineRecord> key) {
        super(child, key, MEDICINE);
    }

    @Override
    public Schema getSchema() {
        return ThangvtmMcare.THANGVTM_MCARE;
    }

    @Override
    public UniqueKey<MedicineRecord> getPrimaryKey() {
        return Keys.KEY_MEDICINE_PRIMARY;
    }

    @Override
    public List<UniqueKey<MedicineRecord>> getKeys() {
        return Arrays.<UniqueKey<MedicineRecord>>asList(Keys.KEY_MEDICINE_PRIMARY);
    }

    @Override
    public Medicine as(String alias) {
        return new Medicine(DSL.name(alias), this);
    }

    @Override
    public Medicine as(Name alias) {
        return new Medicine(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Medicine rename(String name) {
        return new Medicine(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Medicine rename(Name name) {
        return new Medicine(name, null);
    }

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row5<String, String, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }
}
