/*
 * This file is generated by jOOQ.
 */
package vn.mcare.system.repository.model;


import org.jooq.Identity;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;

import vn.mcare.system.repository.model.tables.Admin;
import vn.mcare.system.repository.model.tables.Bill;
import vn.mcare.system.repository.model.tables.ContentLayout;
import vn.mcare.system.repository.model.tables.Customer;
import vn.mcare.system.repository.model.tables.DataList;
import vn.mcare.system.repository.model.tables.District;
import vn.mcare.system.repository.model.tables.ExamineInfo;
import vn.mcare.system.repository.model.tables.HealthMaintenance;
import vn.mcare.system.repository.model.tables.Inventory;
import vn.mcare.system.repository.model.tables.MedicalHistory;
import vn.mcare.system.repository.model.tables.MedicalReport;
import vn.mcare.system.repository.model.tables.MedicalReportDetail;
import vn.mcare.system.repository.model.tables.Medicine;
import vn.mcare.system.repository.model.tables.MedicineBill;
import vn.mcare.system.repository.model.tables.Prescription;
import vn.mcare.system.repository.model.tables.Province;
import vn.mcare.system.repository.model.tables.RegisterExamination;
import vn.mcare.system.repository.model.tables.Service;
import vn.mcare.system.repository.model.tables.ServiceBill;
import vn.mcare.system.repository.model.tables.User;
import vn.mcare.system.repository.model.tables.UserToken;
import vn.mcare.system.repository.model.tables.Ward;
import vn.mcare.system.repository.model.tables.records.AdminRecord;
import vn.mcare.system.repository.model.tables.records.BillRecord;
import vn.mcare.system.repository.model.tables.records.ContentLayoutRecord;
import vn.mcare.system.repository.model.tables.records.CustomerRecord;
import vn.mcare.system.repository.model.tables.records.DataListRecord;
import vn.mcare.system.repository.model.tables.records.DistrictRecord;
import vn.mcare.system.repository.model.tables.records.ExamineInfoRecord;
import vn.mcare.system.repository.model.tables.records.HealthMaintenanceRecord;
import vn.mcare.system.repository.model.tables.records.InventoryRecord;
import vn.mcare.system.repository.model.tables.records.MedicalHistoryRecord;
import vn.mcare.system.repository.model.tables.records.MedicalReportDetailRecord;
import vn.mcare.system.repository.model.tables.records.MedicalReportRecord;
import vn.mcare.system.repository.model.tables.records.MedicineBillRecord;
import vn.mcare.system.repository.model.tables.records.MedicineRecord;
import vn.mcare.system.repository.model.tables.records.PrescriptionRecord;
import vn.mcare.system.repository.model.tables.records.ProvinceRecord;
import vn.mcare.system.repository.model.tables.records.RegisterExaminationRecord;
import vn.mcare.system.repository.model.tables.records.ServiceBillRecord;
import vn.mcare.system.repository.model.tables.records.ServiceRecord;
import vn.mcare.system.repository.model.tables.records.UserRecord;
import vn.mcare.system.repository.model.tables.records.UserTokenRecord;
import vn.mcare.system.repository.model.tables.records.WardRecord;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>thangvtm_mcare</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<DataListRecord, Integer> IDENTITY_DATA_LIST = Identities0.IDENTITY_DATA_LIST;
    public static final Identity<HealthMaintenanceRecord, Integer> IDENTITY_HEALTH_MAINTENANCE = Identities0.IDENTITY_HEALTH_MAINTENANCE;
    public static final Identity<MedicalHistoryRecord, Integer> IDENTITY_MEDICAL_HISTORY = Identities0.IDENTITY_MEDICAL_HISTORY;
    public static final Identity<MedicalReportDetailRecord, Integer> IDENTITY_MEDICAL_REPORT_DETAIL = Identities0.IDENTITY_MEDICAL_REPORT_DETAIL;
    public static final Identity<MedicineBillRecord, Integer> IDENTITY_MEDICINE_BILL = Identities0.IDENTITY_MEDICINE_BILL;
    public static final Identity<PrescriptionRecord, Integer> IDENTITY_PRESCRIPTION = Identities0.IDENTITY_PRESCRIPTION;
    public static final Identity<RegisterExaminationRecord, Integer> IDENTITY_REGISTER_EXAMINATION = Identities0.IDENTITY_REGISTER_EXAMINATION;
    public static final Identity<ServiceBillRecord, Integer> IDENTITY_SERVICE_BILL = Identities0.IDENTITY_SERVICE_BILL;
    public static final Identity<UserTokenRecord, Integer> IDENTITY_USER_TOKEN = Identities0.IDENTITY_USER_TOKEN;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AdminRecord> KEY_ADMIN_PRIMARY = UniqueKeys0.KEY_ADMIN_PRIMARY;
    public static final UniqueKey<BillRecord> KEY_BILL_PRIMARY = UniqueKeys0.KEY_BILL_PRIMARY;
    public static final UniqueKey<ContentLayoutRecord> KEY_CONTENT_LAYOUT_PRIMARY = UniqueKeys0.KEY_CONTENT_LAYOUT_PRIMARY;
    public static final UniqueKey<CustomerRecord> KEY_CUSTOMER_PRIMARY = UniqueKeys0.KEY_CUSTOMER_PRIMARY;
    public static final UniqueKey<DataListRecord> KEY_DATA_LIST_PRIMARY = UniqueKeys0.KEY_DATA_LIST_PRIMARY;
    public static final UniqueKey<DistrictRecord> KEY_DISTRICT_PRIMARY = UniqueKeys0.KEY_DISTRICT_PRIMARY;
    public static final UniqueKey<ExamineInfoRecord> KEY_EXAMINE_INFO_PRIMARY = UniqueKeys0.KEY_EXAMINE_INFO_PRIMARY;
    public static final UniqueKey<HealthMaintenanceRecord> KEY_HEALTH_MAINTENANCE_PRIMARY = UniqueKeys0.KEY_HEALTH_MAINTENANCE_PRIMARY;
    public static final UniqueKey<InventoryRecord> KEY_INVENTORY_PRIMARY = UniqueKeys0.KEY_INVENTORY_PRIMARY;
    public static final UniqueKey<MedicalHistoryRecord> KEY_MEDICAL_HISTORY_PRIMARY = UniqueKeys0.KEY_MEDICAL_HISTORY_PRIMARY;
    public static final UniqueKey<MedicalReportRecord> KEY_MEDICAL_REPORT_PRIMARY = UniqueKeys0.KEY_MEDICAL_REPORT_PRIMARY;
    public static final UniqueKey<MedicalReportDetailRecord> KEY_MEDICAL_REPORT_DETAIL_PRIMARY = UniqueKeys0.KEY_MEDICAL_REPORT_DETAIL_PRIMARY;
    public static final UniqueKey<MedicineRecord> KEY_MEDICINE_PRIMARY = UniqueKeys0.KEY_MEDICINE_PRIMARY;
    public static final UniqueKey<MedicineBillRecord> KEY_MEDICINE_BILL_PRIMARY = UniqueKeys0.KEY_MEDICINE_BILL_PRIMARY;
    public static final UniqueKey<PrescriptionRecord> KEY_PRESCRIPTION_PRIMARY = UniqueKeys0.KEY_PRESCRIPTION_PRIMARY;
    public static final UniqueKey<ProvinceRecord> KEY_PROVINCE_PRIMARY = UniqueKeys0.KEY_PROVINCE_PRIMARY;
    public static final UniqueKey<RegisterExaminationRecord> KEY_REGISTER_EXAMINATION_PRIMARY = UniqueKeys0.KEY_REGISTER_EXAMINATION_PRIMARY;
    public static final UniqueKey<ServiceRecord> KEY_SERVICE_PRIMARY = UniqueKeys0.KEY_SERVICE_PRIMARY;
    public static final UniqueKey<ServiceBillRecord> KEY_SERVICE_BILL_PRIMARY = UniqueKeys0.KEY_SERVICE_BILL_PRIMARY;
    public static final UniqueKey<UserRecord> KEY_USER_PRIMARY = UniqueKeys0.KEY_USER_PRIMARY;
    public static final UniqueKey<UserTokenRecord> KEY_USER_TOKEN_PRIMARY = UniqueKeys0.KEY_USER_TOKEN_PRIMARY;
    public static final UniqueKey<WardRecord> KEY_WARD_PRIMARY = UniqueKeys0.KEY_WARD_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<DataListRecord, Integer> IDENTITY_DATA_LIST = Internal.createIdentity(DataList.DATA_LIST, DataList.DATA_LIST.ID);
        public static Identity<HealthMaintenanceRecord, Integer> IDENTITY_HEALTH_MAINTENANCE = Internal.createIdentity(HealthMaintenance.HEALTH_MAINTENANCE, HealthMaintenance.HEALTH_MAINTENANCE.ID);
        public static Identity<MedicalHistoryRecord, Integer> IDENTITY_MEDICAL_HISTORY = Internal.createIdentity(MedicalHistory.MEDICAL_HISTORY, MedicalHistory.MEDICAL_HISTORY.ID);
        public static Identity<MedicalReportDetailRecord, Integer> IDENTITY_MEDICAL_REPORT_DETAIL = Internal.createIdentity(MedicalReportDetail.MEDICAL_REPORT_DETAIL, MedicalReportDetail.MEDICAL_REPORT_DETAIL.ID);
        public static Identity<MedicineBillRecord, Integer> IDENTITY_MEDICINE_BILL = Internal.createIdentity(MedicineBill.MEDICINE_BILL, MedicineBill.MEDICINE_BILL.ID);
        public static Identity<PrescriptionRecord, Integer> IDENTITY_PRESCRIPTION = Internal.createIdentity(Prescription.PRESCRIPTION, Prescription.PRESCRIPTION.ID);
        public static Identity<RegisterExaminationRecord, Integer> IDENTITY_REGISTER_EXAMINATION = Internal.createIdentity(RegisterExamination.REGISTER_EXAMINATION, RegisterExamination.REGISTER_EXAMINATION.ID);
        public static Identity<ServiceBillRecord, Integer> IDENTITY_SERVICE_BILL = Internal.createIdentity(ServiceBill.SERVICE_BILL, ServiceBill.SERVICE_BILL.ID);
        public static Identity<UserTokenRecord, Integer> IDENTITY_USER_TOKEN = Internal.createIdentity(UserToken.USER_TOKEN, UserToken.USER_TOKEN.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<AdminRecord> KEY_ADMIN_PRIMARY = Internal.createUniqueKey(Admin.ADMIN, "KEY_admin_PRIMARY", new TableField[] { Admin.ADMIN.CIF }, true);
        public static final UniqueKey<BillRecord> KEY_BILL_PRIMARY = Internal.createUniqueKey(Bill.BILL, "KEY_bill_PRIMARY", new TableField[] { Bill.BILL.BILL_ID }, true);
        public static final UniqueKey<ContentLayoutRecord> KEY_CONTENT_LAYOUT_PRIMARY = Internal.createUniqueKey(ContentLayout.CONTENT_LAYOUT, "KEY_content_layout_PRIMARY", new TableField[] { ContentLayout.CONTENT_LAYOUT.CONTENT_KEY }, true);
        public static final UniqueKey<CustomerRecord> KEY_CUSTOMER_PRIMARY = Internal.createUniqueKey(Customer.CUSTOMER, "KEY_customer_PRIMARY", new TableField[] { Customer.CUSTOMER.CIF }, true);
        public static final UniqueKey<DataListRecord> KEY_DATA_LIST_PRIMARY = Internal.createUniqueKey(DataList.DATA_LIST, "KEY_data_list_PRIMARY", new TableField[] { DataList.DATA_LIST.ID }, true);
        public static final UniqueKey<DistrictRecord> KEY_DISTRICT_PRIMARY = Internal.createUniqueKey(District.DISTRICT, "KEY_district_PRIMARY", new TableField[] { District.DISTRICT.ID }, true);
        public static final UniqueKey<ExamineInfoRecord> KEY_EXAMINE_INFO_PRIMARY = Internal.createUniqueKey(ExamineInfo.EXAMINE_INFO, "KEY_examine_info_PRIMARY", new TableField[] { ExamineInfo.EXAMINE_INFO.EXAMINE_ID }, true);
        public static final UniqueKey<HealthMaintenanceRecord> KEY_HEALTH_MAINTENANCE_PRIMARY = Internal.createUniqueKey(HealthMaintenance.HEALTH_MAINTENANCE, "KEY_health_maintenance_PRIMARY", new TableField[] { HealthMaintenance.HEALTH_MAINTENANCE.ID }, true);
        public static final UniqueKey<InventoryRecord> KEY_INVENTORY_PRIMARY = Internal.createUniqueKey(Inventory.INVENTORY, "KEY_inventory_PRIMARY", new TableField[] { Inventory.INVENTORY.INVENTORY_ID }, true);
        public static final UniqueKey<MedicalHistoryRecord> KEY_MEDICAL_HISTORY_PRIMARY = Internal.createUniqueKey(MedicalHistory.MEDICAL_HISTORY, "KEY_medical_history_PRIMARY", new TableField[] { MedicalHistory.MEDICAL_HISTORY.ID }, true);
        public static final UniqueKey<MedicalReportRecord> KEY_MEDICAL_REPORT_PRIMARY = Internal.createUniqueKey(MedicalReport.MEDICAL_REPORT, "KEY_medical_report_PRIMARY", new TableField[] { MedicalReport.MEDICAL_REPORT.MEDICAL_REPORT_ID }, true);
        public static final UniqueKey<MedicalReportDetailRecord> KEY_MEDICAL_REPORT_DETAIL_PRIMARY = Internal.createUniqueKey(MedicalReportDetail.MEDICAL_REPORT_DETAIL, "KEY_medical_report_detail_PRIMARY", new TableField[] { MedicalReportDetail.MEDICAL_REPORT_DETAIL.ID }, true);
        public static final UniqueKey<MedicineRecord> KEY_MEDICINE_PRIMARY = Internal.createUniqueKey(Medicine.MEDICINE, "KEY_medicine_PRIMARY", new TableField[] { Medicine.MEDICINE.MEDICINE_ID }, true);
        public static final UniqueKey<MedicineBillRecord> KEY_MEDICINE_BILL_PRIMARY = Internal.createUniqueKey(MedicineBill.MEDICINE_BILL, "KEY_medicine_bill_PRIMARY", new TableField[] { MedicineBill.MEDICINE_BILL.ID }, true);
        public static final UniqueKey<PrescriptionRecord> KEY_PRESCRIPTION_PRIMARY = Internal.createUniqueKey(Prescription.PRESCRIPTION, "KEY_prescription_PRIMARY", new TableField[] { Prescription.PRESCRIPTION.ID }, true);
        public static final UniqueKey<ProvinceRecord> KEY_PROVINCE_PRIMARY = Internal.createUniqueKey(Province.PROVINCE, "KEY_province_PRIMARY", new TableField[] { Province.PROVINCE.ID }, true);
        public static final UniqueKey<RegisterExaminationRecord> KEY_REGISTER_EXAMINATION_PRIMARY = Internal.createUniqueKey(RegisterExamination.REGISTER_EXAMINATION, "KEY_register_examination_PRIMARY", new TableField[] { RegisterExamination.REGISTER_EXAMINATION.ID }, true);
        public static final UniqueKey<ServiceRecord> KEY_SERVICE_PRIMARY = Internal.createUniqueKey(Service.SERVICE, "KEY_service_PRIMARY", new TableField[] { Service.SERVICE.SERVICE_ID }, true);
        public static final UniqueKey<ServiceBillRecord> KEY_SERVICE_BILL_PRIMARY = Internal.createUniqueKey(ServiceBill.SERVICE_BILL, "KEY_service_bill_PRIMARY", new TableField[] { ServiceBill.SERVICE_BILL.ID }, true);
        public static final UniqueKey<UserRecord> KEY_USER_PRIMARY = Internal.createUniqueKey(User.USER, "KEY_user_PRIMARY", new TableField[] { User.USER.CIF }, true);
        public static final UniqueKey<UserTokenRecord> KEY_USER_TOKEN_PRIMARY = Internal.createUniqueKey(UserToken.USER_TOKEN, "KEY_user_token_PRIMARY", new TableField[] { UserToken.USER_TOKEN.ID }, true);
        public static final UniqueKey<WardRecord> KEY_WARD_PRIMARY = Internal.createUniqueKey(Ward.WARD, "KEY_ward_PRIMARY", new TableField[] { Ward.WARD.ID }, true);
    }
}
