/*
 * This file is generated by jOOQ.
 */
package vn.mcare.system.repository.model;


import vn.mcare.system.repository.model.tables.Admin;
import vn.mcare.system.repository.model.tables.Bill;
import vn.mcare.system.repository.model.tables.ContentLayout;
import vn.mcare.system.repository.model.tables.Customer;
import vn.mcare.system.repository.model.tables.DataList;
import vn.mcare.system.repository.model.tables.District;
import vn.mcare.system.repository.model.tables.ExamineInfo;
import vn.mcare.system.repository.model.tables.HealthMaintenance;
import vn.mcare.system.repository.model.tables.Inventory;
import vn.mcare.system.repository.model.tables.MedicalHistory;
import vn.mcare.system.repository.model.tables.MedicalReport;
import vn.mcare.system.repository.model.tables.MedicalReportDetail;
import vn.mcare.system.repository.model.tables.Medicine;
import vn.mcare.system.repository.model.tables.MedicineBill;
import vn.mcare.system.repository.model.tables.Prescription;
import vn.mcare.system.repository.model.tables.Province;
import vn.mcare.system.repository.model.tables.RegisterExamination;
import vn.mcare.system.repository.model.tables.Service;
import vn.mcare.system.repository.model.tables.ServiceBill;
import vn.mcare.system.repository.model.tables.User;
import vn.mcare.system.repository.model.tables.UserToken;
import vn.mcare.system.repository.model.tables.Ward;


/**
 * Convenience access to all tables in thangvtm_mcare
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>thangvtm_mcare.admin</code>.
     */
    public static final Admin ADMIN = Admin.ADMIN;

    /**
     * The table <code>thangvtm_mcare.bill</code>.
     */
    public static final Bill BILL = Bill.BILL;

    /**
     * The table <code>thangvtm_mcare.content_layout</code>.
     */
    public static final ContentLayout CONTENT_LAYOUT = ContentLayout.CONTENT_LAYOUT;

    /**
     * The table <code>thangvtm_mcare.customer</code>.
     */
    public static final Customer CUSTOMER = Customer.CUSTOMER;

    /**
     * The table <code>thangvtm_mcare.data_list</code>.
     */
    public static final DataList DATA_LIST = DataList.DATA_LIST;

    /**
     * The table <code>thangvtm_mcare.district</code>.
     */
    public static final District DISTRICT = District.DISTRICT;

    /**
     * The table <code>thangvtm_mcare.examine_info</code>.
     */
    public static final ExamineInfo EXAMINE_INFO = ExamineInfo.EXAMINE_INFO;

    /**
     * The table <code>thangvtm_mcare.health_maintenance</code>.
     */
    public static final HealthMaintenance HEALTH_MAINTENANCE = HealthMaintenance.HEALTH_MAINTENANCE;

    /**
     * The table <code>thangvtm_mcare.inventory</code>.
     */
    public static final Inventory INVENTORY = Inventory.INVENTORY;

    /**
     * The table <code>thangvtm_mcare.medical_history</code>.
     */
    public static final MedicalHistory MEDICAL_HISTORY = MedicalHistory.MEDICAL_HISTORY;

    /**
     * The table <code>thangvtm_mcare.medical_report</code>.
     */
    public static final MedicalReport MEDICAL_REPORT = MedicalReport.MEDICAL_REPORT;

    /**
     * The table <code>thangvtm_mcare.medical_report_detail</code>.
     */
    public static final MedicalReportDetail MEDICAL_REPORT_DETAIL = MedicalReportDetail.MEDICAL_REPORT_DETAIL;

    /**
     * The table <code>thangvtm_mcare.medicine</code>.
     */
    public static final Medicine MEDICINE = Medicine.MEDICINE;

    /**
     * The table <code>thangvtm_mcare.medicine_bill</code>.
     */
    public static final MedicineBill MEDICINE_BILL = MedicineBill.MEDICINE_BILL;

    /**
     * The table <code>thangvtm_mcare.prescription</code>.
     */
    public static final Prescription PRESCRIPTION = Prescription.PRESCRIPTION;

    /**
     * The table <code>thangvtm_mcare.province</code>.
     */
    public static final Province PROVINCE = Province.PROVINCE;

    /**
     * The table <code>thangvtm_mcare.register_examination</code>.
     */
    public static final RegisterExamination REGISTER_EXAMINATION = RegisterExamination.REGISTER_EXAMINATION;

    /**
     * The table <code>thangvtm_mcare.service</code>.
     */
    public static final Service SERVICE = Service.SERVICE;

    /**
     * The table <code>thangvtm_mcare.service_bill</code>.
     */
    public static final ServiceBill SERVICE_BILL = ServiceBill.SERVICE_BILL;

    /**
     * The table <code>thangvtm_mcare.user</code>.
     */
    public static final User USER = User.USER;

    /**
     * The table <code>thangvtm_mcare.user_token</code>.
     */
    public static final UserToken USER_TOKEN = UserToken.USER_TOKEN;

    /**
     * The table <code>thangvtm_mcare.ward</code>.
     */
    public static final Ward WARD = Ward.WARD;
}
