/*
 * This file is generated by jOOQ.
 */
package vn.mcare.system.repository.model;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import vn.mcare.system.repository.model.tables.Admin;
import vn.mcare.system.repository.model.tables.Bill;
import vn.mcare.system.repository.model.tables.ContentLayout;
import vn.mcare.system.repository.model.tables.Customer;
import vn.mcare.system.repository.model.tables.DataList;
import vn.mcare.system.repository.model.tables.District;
import vn.mcare.system.repository.model.tables.ExamineInfo;
import vn.mcare.system.repository.model.tables.HealthMaintenance;
import vn.mcare.system.repository.model.tables.Inventory;
import vn.mcare.system.repository.model.tables.MedicalHistory;
import vn.mcare.system.repository.model.tables.MedicalReport;
import vn.mcare.system.repository.model.tables.MedicalReportDetail;
import vn.mcare.system.repository.model.tables.Medicine;
import vn.mcare.system.repository.model.tables.MedicineBill;
import vn.mcare.system.repository.model.tables.Prescription;
import vn.mcare.system.repository.model.tables.Province;
import vn.mcare.system.repository.model.tables.RegisterExamination;
import vn.mcare.system.repository.model.tables.Service;
import vn.mcare.system.repository.model.tables.ServiceBill;
import vn.mcare.system.repository.model.tables.User;
import vn.mcare.system.repository.model.tables.UserToken;
import vn.mcare.system.repository.model.tables.Ward;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ThangvtmMcare extends SchemaImpl {

    private static final long serialVersionUID = 758414908;

    /**
     * The reference instance of <code>thangvtm_mcare</code>
     */
    public static final ThangvtmMcare THANGVTM_MCARE = new ThangvtmMcare();

    /**
     * The table <code>thangvtm_mcare.admin</code>.
     */
    public final Admin ADMIN = Admin.ADMIN;

    /**
     * The table <code>thangvtm_mcare.bill</code>.
     */
    public final Bill BILL = Bill.BILL;

    /**
     * The table <code>thangvtm_mcare.content_layout</code>.
     */
    public final ContentLayout CONTENT_LAYOUT = ContentLayout.CONTENT_LAYOUT;

    /**
     * The table <code>thangvtm_mcare.customer</code>.
     */
    public final Customer CUSTOMER = Customer.CUSTOMER;

    /**
     * The table <code>thangvtm_mcare.data_list</code>.
     */
    public final DataList DATA_LIST = DataList.DATA_LIST;

    /**
     * The table <code>thangvtm_mcare.district</code>.
     */
    public final District DISTRICT = District.DISTRICT;

    /**
     * The table <code>thangvtm_mcare.examine_info</code>.
     */
    public final ExamineInfo EXAMINE_INFO = ExamineInfo.EXAMINE_INFO;

    /**
     * The table <code>thangvtm_mcare.health_maintenance</code>.
     */
    public final HealthMaintenance HEALTH_MAINTENANCE = HealthMaintenance.HEALTH_MAINTENANCE;

    /**
     * The table <code>thangvtm_mcare.inventory</code>.
     */
    public final Inventory INVENTORY = Inventory.INVENTORY;

    /**
     * The table <code>thangvtm_mcare.medical_history</code>.
     */
    public final MedicalHistory MEDICAL_HISTORY = MedicalHistory.MEDICAL_HISTORY;

    /**
     * The table <code>thangvtm_mcare.medical_report</code>.
     */
    public final MedicalReport MEDICAL_REPORT = MedicalReport.MEDICAL_REPORT;

    /**
     * The table <code>thangvtm_mcare.medical_report_detail</code>.
     */
    public final MedicalReportDetail MEDICAL_REPORT_DETAIL = MedicalReportDetail.MEDICAL_REPORT_DETAIL;

    /**
     * The table <code>thangvtm_mcare.medicine</code>.
     */
    public final Medicine MEDICINE = Medicine.MEDICINE;

    /**
     * The table <code>thangvtm_mcare.medicine_bill</code>.
     */
    public final MedicineBill MEDICINE_BILL = MedicineBill.MEDICINE_BILL;

    /**
     * The table <code>thangvtm_mcare.prescription</code>.
     */
    public final Prescription PRESCRIPTION = Prescription.PRESCRIPTION;

    /**
     * The table <code>thangvtm_mcare.province</code>.
     */
    public final Province PROVINCE = Province.PROVINCE;

    /**
     * The table <code>thangvtm_mcare.register_examination</code>.
     */
    public final RegisterExamination REGISTER_EXAMINATION = RegisterExamination.REGISTER_EXAMINATION;

    /**
     * The table <code>thangvtm_mcare.service</code>.
     */
    public final Service SERVICE = Service.SERVICE;

    /**
     * The table <code>thangvtm_mcare.service_bill</code>.
     */
    public final ServiceBill SERVICE_BILL = ServiceBill.SERVICE_BILL;

    /**
     * The table <code>thangvtm_mcare.user</code>.
     */
    public final User USER = User.USER;

    /**
     * The table <code>thangvtm_mcare.user_token</code>.
     */
    public final UserToken USER_TOKEN = UserToken.USER_TOKEN;

    /**
     * The table <code>thangvtm_mcare.ward</code>.
     */
    public final Ward WARD = Ward.WARD;

    /**
     * No further instances allowed
     */
    private ThangvtmMcare() {
        super("thangvtm_mcare", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Admin.ADMIN,
            Bill.BILL,
            ContentLayout.CONTENT_LAYOUT,
            Customer.CUSTOMER,
            DataList.DATA_LIST,
            District.DISTRICT,
            ExamineInfo.EXAMINE_INFO,
            HealthMaintenance.HEALTH_MAINTENANCE,
            Inventory.INVENTORY,
            MedicalHistory.MEDICAL_HISTORY,
            MedicalReport.MEDICAL_REPORT,
            MedicalReportDetail.MEDICAL_REPORT_DETAIL,
            Medicine.MEDICINE,
            MedicineBill.MEDICINE_BILL,
            Prescription.PRESCRIPTION,
            Province.PROVINCE,
            RegisterExamination.REGISTER_EXAMINATION,
            Service.SERVICE,
            ServiceBill.SERVICE_BILL,
            User.USER,
            UserToken.USER_TOKEN,
            Ward.WARD);
    }
}
